language: python

python:
  - 2.7

sudo: false

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.9
      - binutils
      - python-pip
      - graphviz      

env:
  global:
    - SCRIPT="FoBiS.py rule -ex makecoverage"

before_install:
  - git submodule update --init --recursive

install:
  - |
    if [[ ! -d "$HOME/.local/bin" ]]; then
      mkdir "$HOME/.local/bin"
    fi
  - export PATH="$HOME/.local/bin:$PATH"
  - export FC=/usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" && gfortran --version
  - ls -l /usr/bin/gfortran-4.9
  - ln -fs /usr/bin/gcov-4.9 "$HOME/.local/bin/gcov" && gcov --version
  - pip install --upgrade pygooglechart
  - pip install --upgrade graphviz
  - pip install --upgrade FoBiS.py
  - pip install --upgrade markdown-checklist 
  - pip install --upgrade ford
  - pip install --upgrade matplotlib

script:
  - $SCRIPT

after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash <(curl -s https://codecov.io/bash)
  - ./makedoc.sh Fortran-FOSS-Programmers/FOODiE
