b64_decode_up – FoXy
b64_decode_up Interface
Source File
public interface b64_decode_up
Decode unlimited polymorphic variable from base64.
This is an interface for decoding both scalar and array.
Note
Before start to decode anything the library must be initialized. The procedure b64_init must be called at first. The global variable is_b64_initialized can be used to check the status of the initialization.
Usage
For a practical example see the autotest procedure.
Scalar decoding
real(R8P):: decoded ! scalar to be decoded
...
call b64_decode_up(code='AAAAAAAA8D8=',up=decoded)
Array decoding
integer(I8P):: decoded(1:4) ! array to be decoded
...
call b64_decode_up(code='FwAAAAAAAABEAQAAAAAAABBwhAEAAAAAAgAAAAAAAAA=',up=decoded)
Note
If you want to decode heterogenous data (e.g. integer and real numbers), you must use the auxiliary pack_data procedure.
Warning
The decoding of array of strings is admitted only if each string of the array has the same length.
Calls
Module Procedures
public interface b64_decode_up()
Arguments
None
Description
Decode unlimited polymorphic variable from base64.
private subroutine b64_decode_up_a(code, up)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
class(*), intent(out) :: up(1:)
Unlimited polymorphic variable to be decoded.
Description
Decode an unlimited polymorphic array from base64.
Call graph
b64_decode_up calls b64_decode_up, b64_decode_up_a
b64_decode_up_a calls b64_decode_i4_a, b64_decode_i8_a, b64_decode_i2_a, b64_decode_r4_a, b64_decode_r8_a, b64_decode_i1_a, b64_decode_string_a
b64_decode_i4_a calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
byte_size calls byte_size_i1p, byte_size_chr, byte_size_i4p, byte_size_i2p, byte_size_i8p, byte_size_r8p, byte_size_r4p