language: python

sudo: required

python:
  - 2.7

env:
  global:
    - APT_DEPENDS="gfortran-4.9 binutils"
    - PIP_DEPENDS="FoBiS.py markdown-checklist ford"
    - SCRIPT="FoBiS.py rule -ex makecoverage"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y $APT_DEPENDS
  - sudo pip install $PIP_DEPENDS
  - ln -fs /usr/bin/gfortran-4.9 gfortran
  - ln -fs /usr/bin/gcov-4.9 gcov
  - export PATH=".:$PATH"

script:
  - $SCRIPT

after_success:
  - cd $TRAVIS_BUILD_DIR
  - bash <(curl -s https://codecov.io/bash)
  - ./makedoc.sh Fortran-FOSS-Programmers/WenOOF
