average_solution – FOODIE
average_solution Subroutine
17 statements
Source File
subroutine average_solution()
Average the solution over an average grid.
Arguments
None
Called By
Source Code
average_solution
Source Code
  subroutine average_solution()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Average the solution over an average grid.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I_P):: i, ii, i1, i2 !< Counters.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if ((av_Ni>0).and.(av_Ni/=Ni)) then
    if (allocated(av_state)) deallocate(av_state) ; allocate(av_state(1:Np, 1:av_Ni))
    do i=1, av_Ni
      i1 = minloc(array=xcenter, dim=1, mask=(xcenter>=av_xnode(i-1)))
      i2 = maxloc(array=xcenter, dim=1, mask=(xcenter<=av_xnode(i)))
      av_state(:, i) = 0._R_P
      do ii=i1, i2
        av_state(:, i) = av_state(:, i) + final_state(:, ii)
      enddo
      av_state(:, i) = av_state(:, i) / (i2-i1+1)
    enddo
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine average_solution
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz add_oscillation assign_abstract average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_order_2 integrate_order_3 integrate_rk integrate_rk is_admissible is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps min_steps min_steps new_Dt observed_order omega oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie solve sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps used_registers
Call graph
save_results calls average_solution
test_ab calls save_results
test_ls_rk calls save_results
test_euler calls save_results
test_tvd_rk calls save_results
test_leapfrog calls save_results
integrate_euler_1d calls test_ab, test_ls_rk, test_euler, test_tvd_rk, test_leapfrog