b64_encode_up – FoXy
b64_encode_up Subroutine
Source File
public subroutine b64_encode_up(up, code)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: up
Unlimited polymorphic variable to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
Description
Encode an unlimited polymorphic scalar to base64.
Calls
Source Code
  subroutine b64_encode_up(up, code)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Encode an unlimited polymorphic scalar to base64.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(*),                      intent(in)  :: up   !< Unlimited polymorphic variable to be encoded.
  character(len=:), allocatable, intent(out) :: code !< Encoded scalar.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(up)
  type is(real(R8P))
    call b64_encode_R8(n=up,code=code)
  type is(real(R4P))
    call b64_encode_R4(n=up,code=code)
  type is(integer(I8P))
    call b64_encode_I8(n=up,code=code)
  type is(integer(I4P))
    call b64_encode_I4(n=up,code=code)
  type is(integer(I2P))
    call b64_encode_I2(n=up,code=code)
  type is(integer(I1P))
    call b64_encode_I1(n=up,code=code)
  type is(character(*))
    call b64_encode_string(s=up,code=code)
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_encode_up
Call graph
b64_encode_up calls b64_encode_i1, b64_encode_i4, b64_encode_r4, b64_encode_r8, b64_encode_i2, b64_encode_i8, b64_encode_string
b64_encode_i1 calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_string calls encode_bits, byte_size
byte_size calls byte_size_i1p, byte_size_chr, byte_size_i2p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p