b64_decode_string_a – FoXy
b64_decode_string_a Subroutine
Source File
private pure subroutine b64_decode_string_a(code, s)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
character(len=*), intent(out) :: s(1:)
String to be decoded.
Description
Decode a base64 code into an array of strings.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I1P), public, allocatable :: nI1P(:)
One byte integer array containing n.
Source Code
  pure subroutine b64_decode_string_a(code, s)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Decode a base64 code into an array of strings.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in)  :: code    !< Encoded scalar.
  character(*), intent(out) :: s(1:)   !< String to be decoded.
  integer(I1P), allocatable :: nI1P(:) !< One byte integer array containing n.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  allocate(nI1P(1:byte_size(s(1))*size(s,dim=1))) ; nI1P = 0_I1P
  call decode_bits(code=code,bits=nI1P)
  s = transfer(nI1P,s)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_decode_string_a
Call graph
b64_decode_string_a calls byte_size, decode_bits
byte_size calls byte_size_i1p, byte_size_chr, byte_size_i4p, byte_size_i2p, byte_size_i8p, byte_size_r8p, byte_size_r4p
b64_decode_up_a calls b64_decode_string_a
b64_decode_up calls b64_decode_up_a, b64_decode_up
b64_decode calls b64_decode_string_a
autotest calls b64_decode
decode calls b64_decode