compute_amplitude_phase – FOODIE
compute_amplitude_phase Function
Source File
function compute_amplitude_phase(sol) result(ap)
Arguments
Type Intent Optional Attributes Name
real(kind=R_P), intent(in) :: sol(1:2)
Solution.
Return Value real(kind=R_P) (1:2)
Amplitude and phase.
Description
Compute amplitude and phase of the solution.
Called By
Source Code
  function compute_amplitude_phase(sol) result(ap)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Compute amplitude and phase of the solution.
  !---------------------------------------------------------------------------------------------------------------------------------
  real(R_P), intent(IN) :: sol(1:2) !< Solution.
  real(R_P)             :: ap(1:2)  !< Amplitude and phase.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  ap(1) = sqrt(sol(1)**2 + sol(2)**2)
  ap(2) = atan(-sol(1) / sol(2))
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction compute_amplitude_phase
Call graph
leapfrog_solver calls compute_amplitude_phase
save_results calls compute_amplitude_phase
ls_rk_solver calls compute_amplitude_phase
am_solver calls compute_amplitude_phase
ab_solver calls compute_amplitude_phase
bdf_solver calls compute_amplitude_phase
abm_solver calls compute_amplitude_phase
tvd_rk_solver calls compute_amplitude_phase
emd_rk_solver calls compute_amplitude_phase
euler_solver calls compute_amplitude_phase
test_leapfrog calls leapfrog_solver, save_results
perform_errors_analysis calls leapfrog_solver, save_results, ls_rk_solver, am_solver, ab_solver, bdf_solver, abm_solver, tvd_rk_solver, emd_rk_solver
integrate_oscillation calls test_leapfrog, perform_errors_analysis, test_am, test_abm, test_bdf, test_emd_rk, test_tvd_rk, test_ls_rk, test_euler, test_ab
test_am calls save_results, am_solver
test_abm calls save_results, abm_solver
test_bdf calls save_results, bdf_solver
test_emd_rk calls save_results, emd_rk_solver
test_tvd_rk calls save_results, tvd_rk_solver
test_ls_rk calls save_results, ls_rk_solver
test_euler calls save_results, euler_solver
test_ab calls save_results, ab_solver