compute_errors – FOODIE
compute_errors Function
Source File
Variables
ex_sol s v
Source Code
compute_errors
All Procedures
a a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk finalize_rk H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
function compute_errors(solution) result(error_L2)
Arguments
Type Intent Optional Attributes Name
real(kind=R_P), intent(in) :: solution(0:,0:)
Solution at each time step.
Return Value real(kind=R_P) (1:space_dimension)
L2 norm of the numerical error.
Description
Compute the L2 norm of numerical error with respect the exact solution.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=R_P), public :: ex_sol(1:space_dimension)
Exact solution.
integer(kind=I_P), public :: s
Steps/stages counter.
integer(kind=I_P), public :: v
Variables counter.
Source Code
  function compute_errors(solution) result(error_L2)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Compute the L2 norm of numerical error with respect the exact solution.
  !---------------------------------------------------------------------------------------------------------------------------------
  real(R_P), intent(IN) :: solution(0:,0:)             !< Solution at each time step.
  real(R_P)             :: error_L2(1:space_dimension) !< L2 norm of the numerical error.
  real(R_P)             :: ex_sol(1:space_dimension)   !< Exact solution.
  integer(I_P)          :: s                           !< Steps/stages counter.
  integer(I_P)          :: v                           !< Variables counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  error_L2 = 0._R_P
  do s=0, ubound(solution, dim=2)
    ex_sol = exact_solution(t=solution(0, s))
    do v=1, space_dimension
      error_L2(v) = error_L2(v) + (solution(v, s) - ex_sol(v))**2
    enddo
  enddo
  error_L2 = sqrt(error_L2)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction compute_errors
Call graph
compute_errors calls exact_solution
perform_errors_analysis calls compute_errors
integrate_oscillation calls perform_errors_analysis