exact_solution – FOODIE
exact_solution Function
Source File
Source Code
exact_solution
All Procedures
a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
function exact_solution(t) result(ex_sol)
Arguments
Type Intent Optional Attributes Name
real(kind=R_P), intent(in) :: t
Time.
Return Value real(kind=R_P) (1:space_dimension)
Exact solution.
Description
Compute the exact solution.
Called By
Source Code
  function exact_solution(t) result(ex_sol)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Compute the exact solution.
  !---------------------------------------------------------------------------------------------------------------------------------
  real(R_P), intent(IN) :: t                         !< Time.
  real(R_P)             :: ex_sol(1:space_dimension) !< Exact solution.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  ex_sol(1) = initial_state(1) * cos(f * t) - initial_state(2) * sin(f * t)
  ex_sol(2) = initial_state(1) * sin(f * t) + initial_state(2) * cos(f * t)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction exact_solution
Call graph
save_results calls exact_solution
compute_errors calls exact_solution
test_abm calls save_results
perform_errors_analysis calls save_results, compute_errors
test_am calls save_results
test_euler calls save_results
test_ab calls save_results
test_ls_rk calls save_results
test_tvd_rk calls save_results
test_emd_rk calls save_results
test_leapfrog calls save_results
integrate_oscillation calls test_abm, perform_errors_analysis, test_am, test_euler, test_ab, test_ls_rk, test_tvd_rk, test_emd_rk, test_leapfrog