exact_solution_xy – FOODIE
exact_solution_xy Function
7 statements
Source File
private pure function exact_solution_xy(frequency, t) result(ex_sol)
Compute the exact solution on X-Y domain.
Arguments
Type Intent Optional Attributes Name
real(kind=R_P), intent(in) :: frequency
Oscillation frequency.
real(kind=R_P), intent(in) :: t
Time.
Return Value real(kind=R_P) (1:2)
Exact solution.
Called By
Source Code
exact_solution_xy
Source Code
  pure function exact_solution_xy(frequency, t) result(ex_sol)
  !< Compute the exact solution on X-Y domain.
  real(R_P), intent(in) :: frequency   !< Oscillation frequency.
  real(R_P), intent(IN) :: t           !< Time.
  real(R_P)             :: ex_sol(1:2) !< Exact solution.
  ex_sol(1) = initial_state(1) * cos(frequency * t) - initial_state(2) * sin(frequency * t)
  ex_sol(2) = initial_state(1) * sin(frequency * t) + initial_state(2) * cos(frequency * t)
  endfunction exact_solution_xy
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz assign_abstract assign_integrand assign_real average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error check_scheme_has_fast_mode class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt doscillator_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator foodie_integrator_class_names foodie_integrator_schemes H H H H H has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init_rk init_rk initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize_order_s initialize_order_s_1 integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrand_add_integrand integrand_add_integrand_fast integrand_add_integrand_fast integrand_add_real integrand_multiply_integrand integrand_multiply_integrand_fast integrand_multiply_integrand_fast integrand_multiply_real integrand_multiply_real_scalar integrand_multiply_real_scalar_fast integrand_multiply_real_scalar_fast integrand_sub_integrand integrand_sub_real integrand_subtract_integrand_fast integrand_subtract_integrand_fast integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_adams_bashforth integrate_adams_bashforth_fast integrate_adams_bashforth_moulton integrate_adams_moulton integrate_back_df integrate_euler_explicit integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_leapfrog integrate_lmm_ssp integrate_lmm_ssp_vss integrate_lmm_ssp_vss_fast integrate_ms_runge_kutta_ssp integrate_ms_runge_kutta_ssp_fast integrate_order_2 integrate_order_2_fast integrate_order_3 integrate_order_3_fast integrate_order_s integrate_order_s_1 integrate_order_s_1_fast integrate_order_s_fast integrate_rk integrate_rk integrate_runge_kutta_emd integrate_runge_kutta_emd_fast integrate_runge_kutta_ls integrate_runge_kutta_ls_fast integrate_runge_kutta_lssp integrate_runge_kutta_lssp_fast integrate_runge_kutta_ssp integrate_runge_kutta_ssp_fast is_admissible is_available is_class_available is_scheme_available is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported local_error lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real new_Dt observed_order omega output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_add_integrand real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_integrand real_multiply_lorenz real_scalar_multiply_integrand real_sub_integrand reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states registers_number riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie scheme_number sub_burgers sub_euler sub_euler sub_euler sub_lorenz supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes synchronize synchronize synchronize synchronize t_fast t_fast test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
Call graph
error_l2 calls exact_solution_xy
save_results calls exact_solution_xy
integrate_runge_kutta_ssp_fast calls error_l2
integrate_ms_runge_kutta_ssp_fast calls error_l2
integrate_lmm_ssp_vss calls error_l2
integrate_ms_runge_kutta_ssp calls error_l2
integrate_runge_kutta_lssp calls error_l2
integrate_lmm_ssp calls error_l2
integrate_adams_bashforth_fast calls error_l2
integrate_runge_kutta_lssp_fast calls error_l2
integrate_euler_explicit calls error_l2
integrate_runge_kutta_ls_fast calls error_l2
integrate_adams_bashforth calls error_l2
integrate_runge_kutta_ssp calls error_l2
integrate_leapfrog calls error_l2
integrate_runge_kutta_ls calls error_l2
integrate_adams_bashforth_moulton calls error_l2
integrate_runge_kutta_emd_fast calls error_l2
integrate_back_df calls error_l2
integrate_runge_kutta_emd calls error_l2
integrate_adams_moulton calls error_l2
integrate_lmm_ssp_vss_fast calls error_l2
test calls save_results