execute – FOODIE
execute Subroutine
19 statements
Source File
private subroutine execute(self)
Execute test(s).
Arguments
Type Intent Optional Attributes Name
class(oscillation_test), intent(inout) :: self
Test.
Calls
Source Code
execute
Source Code
  subroutine execute(self)
  !< Execute test(s).
  class(oscillation_test), intent(inout) :: self                  !< Test.
  character(99), allocatable             :: integrator_schemes(:) !< Name of FOODIE integrator schemes.
  integer(I_P)                           :: s                     !< Counter.
  call self%initialize
  if (trim(adjustl(self%scheme))/='all') then
     if (is_class_available(scheme=self%scheme)) then
       integrator_schemes = foodie_integrator_schemes(class_name=self%scheme)
     elseif (is_available(scheme=self%scheme)) then
       integrator_schemes = [trim(adjustl(self%scheme))]
     endif
  else
    integrator_schemes = foodie_integrator_schemes()
  endif
  do s=1, size(integrator_schemes, dim=1)
    self%scheme = trim(integrator_schemes(s))
    call self%test(scheme=self%scheme)
  enddo
  endsubroutine execute
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz assign_abstract assign_integrand assign_real average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt doscillator_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator foodie_integrator_class_names foodie_integrator_schemes H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init_rk init_rk initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize_order_s initialize_order_s_1 integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrand_add_integrand integrand_add_integrand_fast integrand_add_integrand_fast integrand_add_real integrand_multiply_integrand integrand_multiply_integrand_fast integrand_multiply_integrand_fast integrand_multiply_real integrand_multiply_real_scalar integrand_multiply_real_scalar_fast integrand_multiply_real_scalar_fast integrand_sub_integrand integrand_sub_real integrand_subtract_integrand_fast integrand_subtract_integrand_fast integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_adams_bashforth integrate_adams_bashforth_fast integrate_adams_bashforth_moulton integrate_adams_moulton integrate_back_df integrate_euler_explicit integrate_fast integrate_leapfrog integrate_lmm_ssp integrate_lmm_ssp_vss integrate_ms_runge_kutta_ssp integrate_order_2 integrate_order_3 integrate_order_s integrate_order_s_1 integrate_rk integrate_rk integrate_runge_kutta_emd integrate_runge_kutta_ls integrate_runge_kutta_lssp integrate_runge_kutta_ssp is_admissible is_available is_class_available is_scheme_available is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported local_error lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real new_Dt observed_order omega output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_add_integrand real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_integrand real_multiply_lorenz real_scalar_multiply_integrand real_sub_integrand reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states registers_number riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie scheme_number sub_burgers sub_euler sub_euler sub_euler sub_lorenz supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes synchronize synchronize synchronize synchronize t_fast t_fast test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
Call graph
execute calls foodie_integrator_schemes, is_class_available, is_available
foodie_integrator_schemes calls supported_schemes
is_class_available calls foodie_integrator_class_names
is_available calls is_class_available, is_scheme_available
foodie_integrator_class_names calls class_name
is_scheme_available calls foodie_integrator_schemes