foodie_integrator_schemes – FOODIE
foodie_integrator_schemes Function
60 statements
Source File
public pure function foodie_integrator_schemes(class_name) result(schemes)
Return the list of all available intergrator schemes, or only the schemes belonging to the given class name.
Note
In the case the class name passed is not available the schemes array is returned not allocated and not warnings are given: it is up to the caller to check the status of the schemes array.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), optional :: class_name
Return only the schemes belogn to the given class.
Return Value character(len=99), allocatable,(:)
Available integrators.
Calls
Called By
Source Code
foodie_integrator_schemes
Source Code
  pure function foodie_integrator_schemes(class_name) result(schemes)
  !< Return the list of all available intergrator schemes, or only the schemes belonging to the given class name.
  !<
  !< @note In the case the class name passed is not available the schemes array is returned not allocated and not warnings are
  !< given: it is up to the caller to check the status of the schemes array.
  character(*), intent(in), optional       :: class_name                  !< Return only the schemes belogn to the given class.
  character(len=99), allocatable           :: schemes(:)                  !< Available integrators.
  type(integrator_adams_bashforth)         :: int_adams_bashforth         !< Integrator Adams Bashforth.
  type(integrator_adams_bashforth_moulton) :: int_adams_bashforth_moulton !< Integrator Adams Bashforth Moulton.
  type(integrator_adams_moulton)           :: int_adams_moulton           !< Integrator Adams Moulton.
  type(integrator_back_df)                 :: int_back_df                 !< Integrator back differentiation formula.
  type(integrator_euler_explicit)          :: int_euler_explicit          !< Integrator euler explicit.
  type(integrator_leapfrog)                :: int_leapfrog                !< Integrator leapfrog.
  type(integrator_lmm_ssp)                 :: int_lmm_ssp                 !< Integrator lmm SSP.
  type(integrator_lmm_ssp_vss)             :: int_lmm_ssp_vss             !< Integrator lmm SSP VSS.
  type(integrator_ms_runge_kutta_ssp)      :: int_ms_runge_kutta_ssp      !< Integrator multistep Runge Kutta ssp.
  type(integrator_runge_kutta_emd)         :: int_runge_kutta_emd         !< Integrator Runge Kutta embdedded.
  type(integrator_runge_kutta_ls)          :: int_runge_kutta_ls          !< Integrator Runge Kutta low storage.
  type(integrator_runge_kutta_lssp)        :: int_runge_kutta_lssp        !< Integrator linear Runge Kutta SSP.
  type(integrator_runge_kutta_ssp)         :: int_runge_kutta_ssp         !< Integrator Runge Kutta SSP.
  if (present(class_name)) then
    if     (trim(int_adams_bashforth%class_name()) == trim(adjustl(class_name))) then
      schemes = int_adams_bashforth%supported_schemes()
    elseif (trim(int_adams_bashforth_moulton%class_name()) == trim(adjustl(class_name))) then
      schemes = int_adams_bashforth_moulton%supported_schemes()
    elseif (trim(int_adams_moulton%class_name()) == trim(adjustl(class_name))) then
      schemes = int_adams_moulton%supported_schemes()
    elseif (trim(int_back_df%class_name()) == trim(adjustl(class_name))) then
      schemes = int_back_df%supported_schemes()
    elseif (trim(int_euler_explicit%class_name()) == trim(adjustl(class_name))) then
      schemes = int_euler_explicit%supported_schemes()
    elseif (trim(int_leapfrog%class_name()) == trim(adjustl(class_name))) then
      schemes = int_leapfrog%supported_schemes()
    elseif (trim(int_lmm_ssp%class_name()) == trim(adjustl(class_name))) then
      schemes = int_lmm_ssp%supported_schemes()
    elseif (trim(int_lmm_ssp_vss%class_name()) == trim(adjustl(class_name))) then
      schemes = int_lmm_ssp_vss%supported_schemes()
    elseif (trim(int_ms_runge_kutta_ssp%class_name()) == trim(adjustl(class_name))) then
      schemes = int_ms_runge_kutta_ssp%supported_schemes()
    elseif (trim(int_runge_kutta_emd%class_name()) == trim(adjustl(class_name))) then
      schemes = int_runge_kutta_emd%supported_schemes()
    elseif (trim(int_runge_kutta_ls%class_name()) == trim(adjustl(class_name))) then
      schemes = int_runge_kutta_ls%supported_schemes()
    elseif (trim(int_runge_kutta_lssp%class_name()) == trim(adjustl(class_name))) then
      schemes = int_runge_kutta_lssp%supported_schemes()
    elseif (trim(int_runge_kutta_ssp%class_name()) == trim(adjustl(class_name))) then
      schemes = int_runge_kutta_ssp%supported_schemes()
    endif
  else
    schemes =           int_adams_bashforth         % supported_schemes()
    schemes = [schemes, int_adams_bashforth_moulton % supported_schemes()]
    schemes = [schemes, int_adams_moulton           % supported_schemes()]
    schemes = [schemes, int_back_df                 % supported_schemes()]
    schemes = [schemes, int_euler_explicit          % supported_schemes()]
    schemes = [schemes, int_leapfrog                % supported_schemes()]
    schemes = [schemes, int_lmm_ssp                 % supported_schemes()]
    schemes = [schemes, int_lmm_ssp_vss             % supported_schemes()]
    schemes = [schemes, int_ms_runge_kutta_ssp      % supported_schemes()]
    schemes = [schemes, int_runge_kutta_emd         % supported_schemes()]
    schemes = [schemes, int_runge_kutta_ls          % supported_schemes()]
    schemes = [schemes, int_runge_kutta_lssp        % supported_schemes()]
    schemes = [schemes, int_runge_kutta_ssp         % supported_schemes()]
  endif
  endfunction foodie_integrator_schemes
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz allocate_integrand_members allocate_integrand_members allocate_integrand_members allocate_integrand_members allocate_integrand_members amplitude_phase assign_abstract assign_integrand assign_integrand assign_integrand assign_multistage assign_multistage_multistep assign_multistep assign_real assign_real assign_real average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error check_scheme_has_fast_mode check_scheme_has_fast_mode check_scheme_has_fast_mode class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_dx compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_multistage destroy_multistage_multistep destroy_multistep destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dt_ratio dU_dt dU_dt dU_dt E E E E E error error error euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution exact_solution exact_solution execute execute execute export_tecplot export_tecplot export_tecplot foodie_integrator_class_names foodie_integrator_factory foodie_integrator_schemes H H H H H has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode has_fast_mode impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init_rk init_rk initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize_order_s initialize_order_s_1 integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrand_add_integrand integrand_add_integrand integrand_add_integrand integrand_add_integrand_fast integrand_add_integrand_fast integrand_add_integrand_fast integrand_add_real integrand_add_real integrand_add_real integrand_dimension integrand_dimension integrand_dimension integrand_multiply_integrand integrand_multiply_integrand integrand_multiply_integrand integrand_multiply_integrand_fast integrand_multiply_integrand_fast integrand_multiply_integrand_fast integrand_multiply_real integrand_multiply_real integrand_multiply_real integrand_multiply_real_scalar integrand_multiply_real_scalar integrand_multiply_real_scalar integrand_multiply_real_scalar_fast integrand_multiply_real_scalar_fast integrand_multiply_real_scalar_fast integrand_sub_integrand integrand_sub_integrand integrand_sub_integrand integrand_sub_real integrand_sub_real integrand_sub_real integrand_subtract_integrand_fast integrand_subtract_integrand_fast integrand_subtract_integrand_fast integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_fast integrate_order_2 integrate_order_2_fast integrate_order_3 integrate_order_3_fast integrate_order_s integrate_order_s_1 integrate_order_s_1_fast integrate_order_s_fast integrate_rk integrate_rk is_admissible is_available is_class_available is_multistage is_multistage is_multistage is_multistep is_multistep is_multistep is_scheme_available is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported local_error local_error local_error lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real new_Dt observed_order observed_order observed_order omega output output output output output output output output output output p p p p p parse_cli parse_cli parse_cli previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_add_integrand real_add_integrand real_add_integrand real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_integrand real_multiply_integrand real_multiply_integrand real_multiply_lorenz real_scalar_multiply_integrand real_scalar_multiply_integrand real_scalar_multiply_integrand real_sub_integrand real_sub_integrand real_sub_integrand reconstruct_interfaces reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states registers_number riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie scheme_number set_cli set_cli set_cli set_sin_wave_initial_state set_square_wave_initial_state stages_number stages_number stages_number steps_number steps_number steps_number sub_burgers sub_euler sub_euler sub_euler sub_lorenz supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes synchronize synchronize synchronize synchronize t_fast t_fast t_fast test test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
Call graph
foodie_integrator_schemes calls supported_schemes
execute calls foodie_integrator_schemes, is_available
is_scheme_available calls foodie_integrator_schemes
is_available calls is_scheme_available