is_admissible – FOODIE
is_admissible Function
23 statements
Source File
public elemental function is_admissible(n, adm_range)
Check if the queried number n is admitted by the admissible range list adm_range.
The admissible range list must be formatted as string containing admissible numbers; valid list are: + adm_range = '1-5' => 1, 2, 3, 4, 5 are admissible numbers; + adm_range = '1,3,5,10-12' => 1, 3, 5, 10, 11, 12 are admissible numbers; + adm_range = '1-4,8,21-22' => 1, 2, 3, 4, 8, 21, 22 are admissible numbers;
You can mix any number of range (min-max format) and/or single number (, comma separated) entries.
Arguments
Type Intent Optional Attributes Name
integer(kind=I_P), intent(in) :: n
Number queried.
character(len=*), intent(in) :: adm_range
Admissible range string.
Return Value logical
Is true is the number is in adm_range.
Calls
Called By
Source Code
is_admissible
Source Code
  elemental function is_admissible(n, adm_range)
  !< Check if the queried number *n* is admitted by the *admissible* range list *adm_range*.
  !<
  !< The admissible range list must be formatted as string containing admissible numbers; valid list are:
  !<+ `adm_range = '1-5'` => 1, 2, 3, 4, 5 are admissible numbers;
  !<+ `adm_range = '1,3,5,10-12'` => 1, 3, 5, 10, 11, 12 are admissible numbers;
  !<+ `adm_range = '1-4,8,21-22'` => 1, 2, 3, 4, 8, 21, 22 are admissible numbers;
  !<
  !< You can mix any number of range (`min-max` format) and/or single number (`,` comma separated) entries.
  integer(I_P), intent(IN)               :: n             !< Number queried.
  character(*), intent(IN)               :: adm_range     !< Admissible range string.
  logical                                :: is_admissible !< Is true is the number is in *adm_range*.
  character(len(adm_range)), allocatable :: tokens(:)     !< Tokens for parsing *adm_range* string.
  character(len(adm_range)), allocatable :: subtokens(:)  !< Tokens for parsing *adm_range* string.
  integer(I_P)                           :: t             !< Counter.
  integer(I_P)                           :: n_parsed(1:2) !< Values parsed from *adm_range*..
  is_admissible = .false.
  call tokenize(string=adm_range, delimiter=',', toks=tokens)
  search_me : do t=1, size(tokens)
    if (index(tokens(t), '-')>0) then
      call tokenize(string=tokens(t), delimiter='-', toks=subtokens)
      read(subtokens(1), *) n_parsed(1)
      read(subtokens(2), *) n_parsed(2)
      is_admissible = (n_parsed(1)<=n.and.n<=n_parsed(2))
    else
      read(tokens(t), *) n_parsed(1)
      is_admissible = (n_parsed(1)==n)
    endif
    if (is_admissible) exit search_me
  enddo search_me
  endfunction is_admissible
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz add_oscillation assign_abstract average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_order_2 integrate_order_3 integrate_rk integrate_rk is_admissible is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps min_steps min_steps new_Dt observed_order omega oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie solve sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps used_registers
Call graph
is_admissible calls tokenize
is_supported calls is_admissible