signature – FOODIE
signature Function
Source File
private function signature(self)
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(in) :: self
CLA data.
Return Value character(len=:), allocatable
Signature.
Description
Get signature.
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=I4P), public :: nargs
Number of arguments consumed by CLA.
integer(kind=I4P), public :: a
Counter.
Source Code
  function signature(self)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Get signature.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(command_line_argument), intent(in) :: self      !< CLA data.
  character(len=:), allocatable            :: signature !< Signature.
  integer(I4P)                             :: nargs     !< Number of arguments consumed by CLA.
  integer(I4P)                             :: a         !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (.not.self%is_hidden) then
    if (self%act==action_store) then
      if (.not.self%is_positional) then
        if (allocated(self%nargs)) then
          select case(self%nargs)
          case('+')
            signature = ' value#1 [value#2 value#3...]'
          case('*')
            signature = ' [value#1 value#2 value#3...]'
          case default
            nargs = cton(str=trim(adjustl(self%nargs)),knd=1_I4P)
            signature = ''
            do a=1, nargs
              signature = signature//' value#'//trim(str(a, .true.))
            enddo
          endselect
        else
          signature = ' value'
        endif
        if (self%is_required) then
          signature = ' '//trim(adjustl(self%switch))//signature
        else
          signature = ' ['//trim(adjustl(self%switch))//signature//']'
        endif
      else
        if (self%is_required) then
          signature = ' value'
        else
          signature = ' [value]'
        endif
      endif
    elseif (self%act==action_store_star) then
      signature = ' [value]'
    else
      if (self%is_required) then
        signature = ' '//trim(adjustl(self%switch))
      else
        signature = ' ['//trim(adjustl(self%switch))//']'
      endif
    endif
  else
    signature = ''
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction signature
Call graph
signature calls cton, str
cton calls ctoi_i2p, ctor_r4p, ctoi_i8p, ctoi_i1p, ctor_r8p, ctoi_i4p
str calls str_i2p, strf_i4p, str_i1p, strf_i1p, strf_r4p, strf_i2p, str_a_i4p, str_bol, str_a_r4p, str_a_i2p, str_a_i8p, str_i4p, strf_i8p, str_r4p, str_a_r8p, str_i8p, str_a_i1p, str_r8p, strf_r8p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p