solve – FOODIE
solve Subroutine
192 statements
Source File
private subroutine solve(solver, frequency, final_time, stages_steps, order, iterations, solution, error, last_step, Dt, tolerance)
Rune the solver selected.
The actual solver is selected by means of the solver input string that must be a valid string as defined into solvers parameter list.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: solver
Selected solver: must be defined into solvers.
real(kind=R_P), intent(in) :: frequency
Oscillation frequency.
real(kind=R_P), intent(in) :: final_time
Final integration time.
integer(kind=I_P), intent(in) :: stages_steps
Number of stages/steps used.
integer(kind=I_P), intent(in) :: order
(Formal) order of accuracy.
integer(kind=I_P), intent(in) :: iterations
Number of fixed point iterations.
real(kind=R_P), intent(out), allocatable :: solution(:,:)
Solution at each time step, X-Y.
real(kind=R_P), intent(out) :: error(1:)
Error (norm L2) with respect the exact solution.
integer(kind=I_P), intent(out) :: last_step
Last time step computed.
real(kind=R_P), intent(in), optional :: Dt
Time step.
real(kind=R_P), intent(in), optional :: tolerance
Local error tolerance.
Calls
Called By
Source Code
solve
Source Code
  subroutine solve(solver, frequency, final_time, stages_steps, order, iterations, solution, error, last_step, Dt, tolerance)
  !< Rune the solver selected.
  !<
  !< The actual solver is selected by means of the *solver* input string that must be a valid string as defined into *solvers*
  !< parameter list.
  character(*),           intent(in)  :: solver        !< Selected solver: must be defined into *solvers*.
  real(R_P),              intent(in)  :: frequency     !< Oscillation frequency.
  real(R_P),              intent(in)  :: final_time    !< Final integration time.
  integer(I_P),           intent(in)  :: stages_steps  !< Number of stages/steps used.
  integer(I_P),           intent(in)  :: order         !< (Formal) order of accuracy.
  integer(I_P),           intent(in)  :: iterations    !< Number of fixed point iterations.
  real(R_P), allocatable, intent(out) :: solution(:,:) !< Solution at each time step, X-Y.
  real(R_P),              intent(out) :: error(1:)     !< Error (norm L2) with respect the exact solution.
  integer(I_P),           intent(out) :: last_step     !< Last time step computed.
  real(R_P), optional,    intent(in)  :: Dt            !< Time step.
  real(R_P), optional,    intent(in)  :: tolerance     !< Local error tolerance.
  ! FOODIE integrators
  type(integrator_adams_bashforth)         :: ab_integrator          !< Adams-Bashforth integrator.
  type(integrator_adams_bashforth_moulton) :: abm_integrator         !< Adams-Bashforth-Moulton integrator.
  type(integrator_adams_moulton)           :: am_integrator          !< Adams-Moulton integrator.
  type(integrator_back_df)                 :: bdf_integrator         !< BDF integrator.
  type(integrator_runge_kutta_emd)         :: emd_rk_integrator      !< Runge-Kutta integrator.
  type(integrator_euler_explicit)          :: euler_integrator       !< Euler integrator.
  type(integrator_leapfrog)                :: lf_integrator          !< Leapfrog integrator.
  type(integrator_lmm_ssp)                 :: lmm_ssp_integrator     !< LMM SSP integrator.
  type(integrator_lmm_ssp_vss)             :: lmm_ssp_vss_integrator !< LMM SSP VSS integrator.
  type(integrator_runge_kutta_ls)          :: ls_rk_integrator       !< Low Storage Runge-Kutta integrator.
  type(integrator_runge_kutta_tvd)         :: tvd_rk_integrator      !< TVD Runge-Kutta integrator.
  ! Auxiliary variables
  integer(I_P), parameter        :: max_rk_stages=5 !< Max RK stages used to init high order multi-step solver.
  type(oscillation)              :: oscillator      !< Oscillation field.
  logical                        :: supported       !< Flag for checking if the selected solver is supported.
  logical                        :: multistep       !< Flag for tagging multi-step class of solvers.
  integer                        :: step_offset     !< Time steps counter offset for slicing previous data array.
  logical                        :: adaptive        !< Flag for tagging time step adaptive class of solvers.
  real(R_P)                      :: Dt_a            !< Adaptive time step.
  real(R_P), allocatable         :: Dts(:)          !< Time steps for variable stepsize methods.
  type(oscillation), allocatable :: rk_stage(:)     !< Runge-Kutta stages.
  type(oscillation), allocatable :: previous(:)     !< Previous time steps solutions.
  type(oscillation)              :: filter          !< Filter displacement.
  integer                        :: step            !< Time steps counter.
  ! initizialize
  call oscillator%init(initial_state=initial_state, frequency=frequency)
  supported = .true.           ! assume that selected solver is supported
  multistep = .false.          ! assume multi-stage solver by default
  if (stages_steps==0) then
    step_offset = 1            ! for 0 step-(a convention)-solver offset is 1
  else
    step_offset = stages_steps ! for >0 step-solver offset is steps
  endif
  adaptive = .false.           ! assume fixed time step by default
  Dt_a = 10000._R_P            ! initial step very large to trigger adaptation
  if (present(Dt)) then
    if (allocated(solution)) deallocate(solution) ; allocate(solution(0:space_dimension, 0:int(final_time/Dt)))
  else
    if (allocated(solution)) deallocate(solution) ; allocate(solution(0:space_dimension, 0:int(final_time/10))) ! hope is enough
  endif
  solution = 0.0_R_P
  solution(1:, 0) = oscillator%output()
  select case(trim(adjustl(solver)))
  case("adams-bashforth")
    supported = ab_integrator%is_supported(stages_steps)
    multistep = .true.
    call ab_integrator%init(steps=stages_steps)
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("adams-bashforth-moulton")
    supported = abm_integrator%is_supported(stages_steps)
    multistep = .true.
    call abm_integrator%init(steps=stages_steps)
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("adams-moulton")
    supported = am_integrator%is_supported(stages_steps)
    multistep = .true.
    call am_integrator%init(steps=stages_steps)
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps+1))
  case("backward-diff-formula")
    supported = bdf_integrator%is_supported(stages_steps)
    multistep = .true.
    call bdf_integrator%init(steps=stages_steps)
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps+1))
  case("emd-runge-kutta")
    supported = emd_rk_integrator%is_supported(stages_steps)
    adaptive = .true.
    call emd_rk_integrator%init(stages=stages_steps, tolerance=tolerance)
    if (allocated(rk_stage)) deallocate(rk_stage) ; allocate(rk_stage(1:stages_steps))
  case("euler")
    supported = euler_integrator%is_supported(stages_steps)
  case("leapfrog")
    supported = lf_integrator%is_supported(stages_steps)
    multistep = .true.
    call lf_integrator%init()
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("leapfrog-raw")
    supported = lf_integrator%is_supported(stages_steps)
    multistep = .true.
    call lf_integrator%init()
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("lmm-ssp")
    supported = lmm_ssp_integrator%is_supported(stages_steps)
    multistep = .true.
    call lmm_ssp_integrator%init(steps=stages_steps)
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("lmm-ssp-vss")
    supported = lmm_ssp_vss_integrator%is_supported(steps=stages_steps, order=order)
    multistep = .true.
    call lmm_ssp_vss_integrator%init(steps=stages_steps, order=order)
    if (allocated(Dts)) deallocate(Dts) ; allocate(Dts(1:stages_steps)) ; Dts = Dt
    if (allocated(previous)) deallocate(previous) ; allocate(previous(1:stages_steps))
  case("ls-runge-kutta")
    supported = ls_rk_integrator%is_supported(stages_steps)
    call ls_rk_integrator%init(stages=stages_steps)
    if (allocated(rk_stage)) deallocate(rk_stage) ; allocate(rk_stage(1:ls_rk_integrator%used_registers()))
  case("tvd-runge-kutta")
    supported = tvd_rk_integrator%is_supported(stages_steps)
    call tvd_rk_integrator%init(stages=stages_steps)
    if (allocated(rk_stage)) deallocate(rk_stage) ; allocate(rk_stage(1:stages_steps))
  endselect
  if (multistep) then
    call tvd_rk_integrator%init(stages=max_rk_stages)
    if (allocated(rk_stage)) deallocate(rk_stage) ; allocate(rk_stage(1:max_rk_stages))
  endif
  if (.not.supported) then
    print "(A)", 'The solver '//trim(adjustl(solver))//' does not support '//trim(str(stages_steps, .true.))//' stages/steps'
    if (allocated(solution)) deallocate(solution)
    return
  endif
  ! integrate
  step = 0
  do while(solution(0, step)<final_time.and.step<ubound(solution, dim=2))
    step = step + 1
    ! advance oscillator
    if (multistep) then
      if (stages_steps>=step) then
        call tvd_rk_integrator%integrate(U=oscillator, stage=rk_stage, Dt=Dt, t=solution(0, step))
        previous(step) = oscillator
      else
        select case(trim(adjustl(solver)))
        case("adams-bashforth")
          call ab_integrator%integrate(U=oscillator,      &
                                       previous=previous, &
                                       Dt=Dt,             &
                                       t=solution(0, step-step_offset:step-1))
        case("adams-bashforth-moulton")
          call abm_integrator%integrate(U=oscillator,      &
                                        previous=previous, &
                                        Dt=Dt,             &
                                        t=solution(0, step-step_offset:step-1))
        case("adams-moulton")
          if (iterations>1) then
            call am_integrator%integrate(U=oscillator,                          &
                                         previous=previous,                     &
                                         Dt=Dt,                                 &
                                         t=solution(0,step-step_offset:step-1), &
                                         iterations=iterations)
          else
            call am_integrator%integrate(U=oscillator,                          &
                                         previous=previous,                     &
                                         Dt=Dt,                                 &
                                         t=solution(0,step-step_offset:step-1))
          endif
        case("backward-diff-formula")
          if (iterations>1) then
            call bdf_integrator%integrate(U=oscillator,                          &
                                          previous=previous,                     &
                                          Dt=Dt,                                 &
                                          t=solution(0,step-step_offset:step-1), &
                                          iterations=iterations)
          else
            call bdf_integrator%integrate(U=oscillator,                          &
                                          previous=previous,                     &
                                          Dt=Dt,                                 &
                                          t=solution(0,step-step_offset:step-1))
          endif
        case("leapfrog")
          call lf_integrator%integrate(U=oscillator,      &
                                       previous=previous, &
                                       Dt=Dt,             &
                                       t=solution(0, step))
        case("leapfrog-raw")
          call lf_integrator%integrate(U=oscillator,        &
                                       previous=previous,   &
                                       Dt=Dt,               &
                                       t=solution(0, step), &
                                       filter=filter)
        case("lmm-ssp")
          call lmm_ssp_integrator%integrate(U=oscillator,      &
                                            previous=previous, &
                                            Dt=Dt,             &
                                            t=solution(0, step-step_offset:step-1))
        case("lmm-ssp-vss")
          call lmm_ssp_vss_integrator%integrate(U=oscillator,      &
                                                previous=previous, &
                                                Dt=Dts,            &
                                                t=solution(0, step-step_offset:step-1))
        endselect
      endif
    else
      select case(trim(adjustl(solver)))
      case("emd-runge-kutta")
        call emd_rk_integrator%integrate(U=oscillator, stage=rk_stage, Dt=Dt_a, t=solution(0, step))
      case("euler")
        call euler_integrator%integrate(U=oscillator, Dt=Dt, t=solution(0, step))
      case("ls-runge-kutta")
        call ls_rk_integrator%integrate(U=oscillator, stage=rk_stage, Dt=Dt, t=solution(0, step))
      case("tvd-runge-kutta")
        call tvd_rk_integrator%integrate(U=oscillator, stage=rk_stage, Dt=Dt, t=solution(0, step))
      endselect
    endif
    ! update time
    if (adaptive) then
      solution(0, step) = solution(0, step - 1) + Dt_a
    else
      solution(0, step) = step * Dt
    endif
    ! store step solution
    solution(1:, step) = oscillator%output()
  enddo
  last_step = step
  error = error_L2(frequency=frequency, solution=solution(:, 0:last_step))
  endsubroutine solve
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz add_oscillation assign_abstract average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_order_2 integrate_order_3 integrate_rk integrate_rk is_admissible is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real max_stages max_stages max_stages max_stages_steps max_steps max_steps max_steps max_steps max_steps max_steps max_steps min_stages min_stages min_stages min_stages_steps min_steps min_steps min_steps min_steps min_steps min_steps min_steps new_Dt observed_order omega oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie solve sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps used_registers
Call graph
solve calls error_l2, str
error_l2 calls exact_solution_xy
test calls solve