test_am – FOODIE
test_am Subroutine
Source File
Variables
am_steps solution s steps_range output title
Source Code
test_am
All Procedures
a a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk finalize_rk H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
subroutine test_am(steps)
Arguments
Type Intent Optional Attributes Name
integer(kind=I_P), intent(in) :: steps
Number of steps used: if negative all AB solvers are used.
Description
Test implicit Adams-Moulton class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: am_steps = 3
Adams-Moulton steps number.
real(kind=R_P), public, allocatable :: solution(:,:)
Solution at each time step.
integer(kind=I_P), public :: s
AM steps counter.
integer(kind=I_P), public :: steps_range(1:2)
Steps used.
character(len=:), public, allocatable :: output
Output files basename.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_am(steps)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test implicit Adams-Moulton class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I_P), intent(IN)      :: steps            !< Number of steps used: if negative all AB solvers are used.
  integer, parameter            :: am_steps=3       !< Adams-Moulton steps number.
  real(R_P), allocatable        :: solution(:,:)    !< Solution at each time step.
  integer(I_P)                  :: s                !< AM steps counter.
  integer(I_P)                  :: steps_range(1:2) !< Steps used.
  character(len=:), allocatable :: output           !< Output files basename.
  character(len=:), allocatable :: title            !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  solver = 'adams-moulton'
  call init(output=output, solution=solution)
  print "(A)", 'Integrating Oscillation equations by means of Adams-Moulton class of solvers'
  steps_range = [0, am_steps] ; if (steps>0) steps_range = [steps, steps]
  do s=steps_range(1), steps_range(2)
    print "(A)", ' AM-'//trim(str(.true.,s))
    title = 'Oscillation equation integration, implicit Adams-Moulton, t='//str(n=t_final)//&
            ' steps='//trim(str(.true., s))
    if (implicit_iterations>1) then
      call am_solver(steps=s, solution=solution, iterations=implicit_iterations)
    else
      call am_solver(steps=s, solution=solution)
    endif
    call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
  enddo
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_am
Call graph
test_am calls save_results, am_solver, init, str
save_results calls exact_solution
init calls str, strz
integrate_oscillation calls test_am