test_tvd_rk – FOODiE
test_tvd_rk Subroutine
Source File
Variables
rk_stages solution s stages_range output title
Source Code
test_tvd_rk
All Procedures
a a ab_solver abm_solver add_burgers add_euler add_euler add_lorenz add_oscillation average_solution burgers_assign_burgers burgers_assign_real burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E estimate_orders euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize H H impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init integrate integrate integrate integrate integrate integrate integrate leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver oscillation_assign_oscillation oscillation_multiply_oscillation oscillation_multiply_real output output output output output p p perform_errors_analysis previous_step previous_step previous_step previous_step primitive2conservative primitive2conservative print_analysis r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver save_results save_results save_results save_results save_results save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_lorenz sub_oscillation test_ab test_ab test_ab test_ab test_abm test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps update_previous_steps
subroutine test_tvd_rk(stages)
Arguments
Type Intent Optional Attributes Name
integer(kind=I_P), intent(in) :: stages
Number of stages used: if negative all RK solvers are used.
Description
Test explicit TVD/SSP Runge-Kutta class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: rk_stages = 5
Runge-Kutta stages number.
real(kind=R_P), public, allocatable :: solution(:,:)
Solution at each time step.
integer(kind=I_P), public :: s
RK stages counter.
integer(kind=I_P), public :: stages_range(1:2)
Stages used.
character(len=:), public, allocatable :: output
Output files basename.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_tvd_rk(stages)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit TVD/SSP Runge-Kutta class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I_P), intent(IN)      :: stages            !< Number of stages used: if negative all RK solvers are used.
  integer, parameter            :: rk_stages=5       !< Runge-Kutta stages number.
  real(R_P), allocatable        :: solution(:,:)     !< Solution at each time step.
  integer(I_P)                  :: s                 !< RK stages counter.
  integer(I_P)                  :: stages_range(1:2) !< Stages used.
  character(len=:), allocatable :: output            !< Output files basename.
  character(len=:), allocatable :: title             !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  solver = 'tvd-runge-kutta'
  call init(output=output, solution=solution)
  print "(A)", 'Integrating Oscillation equations by means of TVD/SSP Runge-Kutta class of solvers'
  stages_range = [1, rk_stages] ; if (stages>0) stages_range = [stages, stages]
  do s=stages_range(1), stages_range(2)
    if (s==4) cycle ! 4 stages not yet implemented
    print "(A)", ' RK-'//trim(str(.true.,s))
    title = 'Oscillation equation integration, explicit TVD/SSP Runge-Kutta, t='//str(n=t_final)//' steps='//trim(str(.true., s))
    call tvd_rk_solver(stages=s, solution=solution)
    call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
  enddo
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_tvd_rk
Call graph
test_tvd_rk calls init, save_results, str, tvd_rk_solver
init calls str, strz
save_results calls exact_solution
integrate_oscillation calls test_tvd_rk