test_euler – FOODIE
test_euler Subroutine
Source File
Variables
euler_integrator dt t
Source Code
test_euler
All Procedures
a a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk finalize_rk H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init init_rk init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
subroutine test_euler()
Arguments
None
Description
Test explicit forward Euler ODE solver.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(euler_explicit_integrator), public :: euler_integrator
Euler integrator.
real(kind=R_P), public :: dt
Time step.
real(kind=R_P), public :: t
Time.
Source Code
  subroutine test_euler()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit forward Euler ODE solver.
  !---------------------------------------------------------------------------------------------------------------------------------
  type(euler_explicit_integrator) :: euler_integrator !< Euler integrator.
  real(R_P)                       :: dt               !< Time step.
  real(R_P)                       :: t                !< Time.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print "(A)", 'Integrating Burgers equation by means of explicit Euler solver'
  call domain%init(initial_state=initial_state, Ni=Ni, h=h, nu=nu)
  dt = domain%dt(CFL=CFL)
  t = 0._R_P
  do while(t<t_final)
    call euler_integrator%integrate(U=domain, dt=dt, t=t)
    t = t + dt
  enddo
  final_state = domain%output()
  call save_results(title='FOODIE test: Burgers equation integration, t='//str(n=t_final)//' explicit Euler', &
                    filename='burgers_integration-euler')
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_euler
Call graph
test_euler calls save_results, str
integrate_burgers calls test_euler