test – FOODIE
test Subroutine
96 statements
Source File
private subroutine test(self, scheme)
Perform the test.
Arguments
Type Intent Optional Attributes Name
class(oscillation_test), intent(in) :: self
Test.
character(len=*), intent(in) :: scheme
Selected scheme.
Calls
Source Code
test
Source Code
  subroutine test(self, scheme)
  !< Perform the test.
  class(oscillation_test), intent(in)      :: self                        !< Test.
  character(*),            intent(in)      :: scheme                      !< Selected scheme.
  procedure(integrate_interface), pointer  :: integrate => null()         !< Actual integrate procedure.
  type(integrator_runge_kutta_emd)         :: int_runge_kutta_emd         !< Runge Kutta embedded integrator.
  real(R_P), allocatable                   :: solution(:,:)               !< Solution at each time step.
  real(R_P), allocatable                   :: error(:,:)                  !< Error (norm L2) with respect the exact solution.
  real(R_P), allocatable                   :: order(:,:)                  !< Observed order based on subsequent refined solutions.
  real(R_P), allocatable                   :: Dt_mean(:)                  !< Mean time steps used for adaptive solver solutions.
  integer(I_P)                             :: last_step                   !< Last time step computed.
  integer(I_P)                             :: t                           !< Counter.
  print "(A)", trim(adjustl(scheme))
  call initialize_test
  if (index(trim(adjustl(scheme)), trim(int_runge_kutta_emd%class_name())) > 0) then
    do t=1, size(self%tolerance, dim=1)
      call integrate(scheme=scheme,              &
                     frequency=self%frequency,   &
                     final_time=self%final_time, &
                     solution=solution,          &
                     error=error(:, t),          &
                     last_step=last_step,        &
                     tolerance=self%tolerance(t))
      Dt_mean(t) = self%final_time/real(last_step, kind=R_P)
      if (allocated(solution)) then
        print "(A,I10,A,F10.3,A,F10.3,A,E10.3,A,E10.3)", "    steps: ", last_step,              &
                                                         "    Dt: ", Dt_mean(t),                &
                                                         ", f*Dt: ", self%frequency*Dt_mean(t), &
                                                         ", E(x): ", error(1, t), ", E(y): ", error(2, t)
        if (self%errors_analysis.and.t>1) then
          order(:, t-1) = observed_order(error=error(:, t-1:t), Dt=Dt_mean(t-1:t))
          print "(A,F10.2,A,F10.2)", "      Observed order, O(x): ", order(1, t-1), ", O(y): " , order(2, t-1)
        endif
        call save_results(results=self%results,         &
                          output_cli=self%output_cli,   &
                          scheme=trim(adjustl(scheme)), &
                          frequency=self%frequency,     &
                          solution=solution(:, 0:last_step))
      endif
    enddo
  else
    do t=1, size(self%Dt, dim=1)
      call integrate(scheme=scheme,              &
                     frequency=self%frequency,   &
                     final_time=self%final_time, &
                     solution=solution,          &
                     error=error(:, t),          &
                     last_step=last_step,        &
                     Dt=self%Dt(t),              &
                     stages=self%stages,         &
                     iterations=self%implicit_iterations)
      if (allocated(solution)) then
        print "(A,I10,A,F10.3,A,F10.3,A,E10.3,A,E10.3)", "    steps: ", last_step,              &
                                                         "    Dt: ", self%Dt(t),                &
                                                         ", f*Dt: ", self%frequency*self%Dt(t), &
                                                         ", E(x): ", error(1, t), ", E(y): ", error(2, t)
        if (self%errors_analysis.and.t>1) then
          order(:, t-1) = observed_order(error=error(:, t-1:t), Dt=self%Dt(t-1:t))
          print "(A,F10.2,A,F10.2)", "      Observed order, O(x): ", order(1, t-1), ", O(y): " , order(2, t-1)
        endif
        call save_results(results=self%results,         &
                          output_cli=self%output_cli,   &
                          scheme=trim(adjustl(scheme)), &
                          frequency=self%frequency,     &
                          solution=solution(:, 0:last_step))
      endif
    enddo
  endif
  contains
    subroutine initialize_test
    !< Intialize test.
    type(integrator_adams_bashforth)         :: int_adams_bashforth         !< Adams Bashforth integrator.
    type(integrator_adams_bashforth_moulton) :: int_adams_bashforth_moulton !< Adams Bashforth Moulton  integrator.
    type(integrator_adams_moulton)           :: int_adams_moulton           !< Adams Moulton integrator.
    type(integrator_back_df)                 :: int_back_df                 !< Back differentiation formula integrator.
    type(integrator_euler_explicit)          :: int_euler_explicit          !< Euler explicit integrator.
    type(integrator_leapfrog)                :: int_leapfrog                !< Leapfrog integrator.
    type(integrator_lmm_ssp)                 :: int_lmm_ssp                 !< LMM SSP integrator.
    type(integrator_lmm_ssp_vss)             :: int_lmm_ssp_vss             !< LMM SSP VSS integrator.
    type(integrator_ms_runge_kutta_ssp)      :: int_ms_runge_kutta_ssp      !< Multistep Runge-Kutta SSP integrator.
    type(integrator_runge_kutta_ls)          :: int_runge_kutta_ls          !< Runge-Kutta low storage integrator.
    type(integrator_runge_kutta_lssp)        :: int_runge_kutta_lssp        !< Linear Runge-Kutta SSP integrator.
    type(integrator_runge_kutta_ssp)         :: int_runge_kutta_ssp         !< Runge Kutta-SSP integrator.
    if     (index(trim(adjustl(scheme)), trim(int_adams_bashforth_moulton%class_name())) > 0) then
       integrate => integrate_adams_bashforth_moulton
    elseif (index(trim(adjustl(scheme)), trim(int_adams_bashforth%class_name())) > 0) then
       integrate => integrate_adams_bashforth
    elseif (index(trim(adjustl(scheme)), trim(int_adams_moulton%class_name())) > 0) then
       integrate => integrate_adams_moulton
    elseif (index(trim(adjustl(scheme)), trim(int_back_df%class_name())) > 0) then
       integrate => integrate_back_df
    elseif (index(trim(adjustl(scheme)), trim(int_euler_explicit%class_name())) > 0) then
       integrate => integrate_euler_explicit
    elseif (index(trim(adjustl(scheme)), trim(int_leapfrog%class_name())) > 0) then
       integrate => integrate_leapfrog
    elseif (index(trim(adjustl(scheme)), trim(int_lmm_ssp_vss%class_name())) > 0) then
       integrate => integrate_lmm_ssp_vss
    elseif (index(trim(adjustl(scheme)), trim(int_lmm_ssp%class_name())) > 0) then
       integrate => integrate_lmm_ssp
    elseif (index(trim(adjustl(scheme)), trim(int_ms_runge_kutta_ssp%class_name())) > 0) then
       integrate => integrate_ms_runge_kutta_ssp
    elseif (index(trim(adjustl(scheme)), trim(int_runge_kutta_emd%class_name())) > 0) then
       integrate => integrate_runge_kutta_emd
    elseif (index(trim(adjustl(scheme)), trim(int_runge_kutta_lssp%class_name())) > 0) then
       integrate => integrate_runge_kutta_lssp
    elseif (index(trim(adjustl(scheme)), trim(int_runge_kutta_ls%class_name())) > 0) then
       integrate => integrate_runge_kutta_ls
    elseif (index(trim(adjustl(scheme)), trim(int_runge_kutta_ssp%class_name())) > 0) then
       integrate => integrate_runge_kutta_ssp
    endif
    if (index(trim(adjustl(scheme)), trim(int_runge_kutta_emd%class_name())) > 0) then
      if (allocated(error)) deallocate(error) ; allocate(error(1:space_dimension, 1:size(self%tolerance)))
      if (allocated(Dt_mean)) deallocate(Dt_mean) ; allocate(Dt_mean(1:size(error, dim=2)))
    else
      if (allocated(error)) deallocate(error) ; allocate(error(1:space_dimension, 1:size(self%Dt)))
    endif
    error = 0.0_R_P
    if (self%errors_analysis) then
      if (allocated(order)) deallocate(order) ; allocate(order(1:space_dimension, 1:size(error, dim=2)-1))
    endif
    endsubroutine initialize_test
  endsubroutine test
All Procedures
a a a a a add_burgers add_euler add_euler add_euler add_lorenz assign_abstract assign_integrand assign_real average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real check_error class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name class_name compute_dt compute_dt compute_dt compute_dt compute_dt compute_dt compute_inter_states compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx description description description description description description description description description description description description description destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_abstract destroy_rk destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt doscillator_dt dt_ratio E E E E E error_L2 euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real exact_solution_xy execute foodie_integrator foodie_integrator_class_names foodie_integrator_schemes H H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init_rk init_rk initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize initialize_order_s initialize_order_s_1 integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integr_assign_integr integrand_add_integrand integrand_add_real integrand_multiply_integrand integrand_multiply_real integrand_multiply_real_scalar integrand_sub_integrand integrand_sub_real integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate integrate_adams_bashforth integrate_adams_bashforth_moulton integrate_adams_moulton integrate_back_df integrate_euler_explicit integrate_leapfrog integrate_lmm_ssp integrate_lmm_ssp_vss integrate_ms_runge_kutta_ssp integrate_order_2 integrate_order_3 integrate_order_s integrate_order_s_1 integrate_rk integrate_rk integrate_runge_kutta_emd integrate_runge_kutta_ls integrate_runge_kutta_lssp integrate_runge_kutta_ssp is_admissible is_available is_class_available is_scheme_available is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported is_supported local_error lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real new_Dt observed_order omega output output output output output output output output p p p p p previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative primitive2conservative r r r r r real_add_integrand real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_integrand real_multiply_lorenz real_scalar_multiply_integrand real_sub_integrand reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states registers_number riemann_solver riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie save_time_serie scheme_number sub_burgers sub_euler sub_euler sub_euler sub_lorenz supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes supported_schemes synchronize synchronize synchronize synchronize test test_ab test_ab test_ab test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk tokenize trigger_error update_previous update_previous update_previous update_previous update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
Call graph
test calls observed_order, save_results
save_results calls strz, exact_solution_xy