test_leapfrog – FOODIE
test_leapfrog Subroutine
Source File
subroutine test_leapfrog()
Arguments
None
Description
Test explicit leapfrog class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(tvd_runge_kutta_integrator), public :: rk_integrator
Runge-Kutta integrator.
integer, public, parameter :: rk_stages = 2
Runge-Kutta stages number.
type(euler_1D), public :: rk_stage(1:rk_stages)
Runge-Kutta stages.
type(euler_1D), public :: filter
Filter displacement.
type(leapfrog_integrator), public :: lf_integrator
Leapfrog integrator.
type(euler_1D), public :: previous(1:2)
Previous time steps solutions.
integer, public :: step
Time steps counter.
real(kind=R_P), public :: dt
Time step.
real(kind=R_P), public :: t
Time.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_leapfrog()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit leapfrog class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  type(tvd_runge_kutta_integrator) :: rk_integrator         !< Runge-Kutta integrator.
  integer, parameter               :: rk_stages=2           !< Runge-Kutta stages number.
  type(euler_1D)                   :: rk_stage(1:rk_stages) !< Runge-Kutta stages.
  type(euler_1D)                   :: filter                !< Filter displacement.
  type(leapfrog_integrator)        :: lf_integrator         !< Leapfrog integrator.
  type(euler_1D)                   :: previous(1:2)         !< Previous time steps solutions.
  integer                          :: step                  !< Time steps counter.
  real(R_P)                        :: dt                    !< Time step.
  real(R_P)                        :: t                     !< Time.
  character(len=:), allocatable    :: title                 !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print "(A)", 'Integrating 1D Euler equations by means of leapfrog (RAW filtered) class of solvers'
  title = '1D Euler equations integration, explicit leapfrog (RAW filtered), t='//str(n=t_final)
  call lf_integrator%init(nu=1.0_R_P, alpha=0._R_P)
  call rk_integrator%init(stages=rk_stages)
  call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, steps=2, ord=3)
  t = 0._R_P
  call save_time_serie(title=title, filename=output//'-time_serie.dat', t=t)
  step = 1
  do while(t<t_final)
    if (verbose) print "(A)", '    Time step: '//str(n=dt)//', Time: '//str(n=t)
    dt = domain%dt(Nmax=0, Tmax=t_final, t=t, CFL=0.1_R_P*CFL)
    if (2>=step) then
      ! the time steps from 1 to s - 1 must be computed with other scheme...
      call rk_integrator%integrate(U=domain, stage=rk_stage, dt=dt, t=t)
      previous(step) = domain
    else
      call lf_integrator%integrate(U=domain, previous=previous, dt=dt, t=t, filter=filter)
    endif
    t = t + dt
    step = step + 1
    call save_time_serie(t=t)
  enddo
  call save_time_serie(t=t, finish=.true.)
  call save_results(title=title, basename=output)
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_leapfrog
Call graph
test_leapfrog calls save_time_serie, str, save_results
save_time_serie calls str
str calls str_a_i4p, str_a_r4p, str_i4p, str_r8p, strf_i1p, strf_i8p, strf_r4p, str_bol, strf_i4p, str_a_i1p, strf_i2p, str_i8p, str_i1p, strf_r8p, str_a_r8p, str_r4p, str_a_i8p, str_a_i2p, str_i2p
save_results calls str, average_solution
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p
integrate_euler_1d calls test_leapfrog