b64_decode_up_a – FoXy
b64_decode_up_a Subroutine
Source File
private subroutine b64_decode_up_a(code, up)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded array.
class(*), intent(out) :: up(1:)
Unlimited polymorphic variable to be decoded.
Description
Decode an unlimited polymorphic array from base64.
Calls
Called By
Source Code
  subroutine b64_decode_up_a(code, up)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Decode an unlimited polymorphic array from base64.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in)  :: code   !< Encoded array.
  class(*),     intent(out) :: up(1:) !< Unlimited polymorphic variable to be decoded.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(up)
  type is(real(R8P))
    call b64_decode_R8_a(code=code,n=up)
  type is(real(R4P))
    call b64_decode_R4_a(code=code,n=up)
  type is(integer(I8P))
    call b64_decode_I8_a(code=code,n=up)
  type is(integer(I4P))
    call b64_decode_I4_a(code=code,n=up)
  type is(integer(I2P))
    call b64_decode_I2_a(code=code,n=up)
  type is(integer(I1P))
    call b64_decode_I1_a(code=code,n=up)
  type is(character(*))
    call b64_decode_string_a(code=code,s=up)
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_decode_up_a
Call graph
b64_decode_up_a calls b64_decode_r4_a, b64_decode_string_a, b64_decode_i2_a, b64_decode_i1_a, b64_decode_r8_a, b64_decode_i8_a, b64_decode_i4_a
b64_decode_r4_a calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
b64_decode_i2_a calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i4_a calls decode_bits
byte_size calls byte_size_i1p, byte_size_r8p, byte_size_r4p, byte_size_i2p, byte_size_i8p, byte_size_i4p, byte_size_chr
b64_decode_up calls b64_decode_up_a, b64_decode_up