ctor_R4P – FOODIE
ctor_R4P Function
Source File
private function ctor_R4P(str, knd, pref, error) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
character(len=*), intent(in), optional :: pref
Prefixing string.
integer(kind=I4P), intent(out), optional :: error
Error trapping flag: 0 no errors, >0 error occurs.
Return Value real(kind=R4P)
Number returned.
Description
Convert string to real.
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I4P), public :: err
Error trapping flag: 0 no errors, >0 error occurs.
character(len=:), public, allocatable :: prefd
Prefixing string.
Source Code
  function ctor_R4P(str, knd, pref, error) result(n)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert string to real.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*),           intent(in)  :: str   !< String containing input number.
  real(R4P),              intent(in)  :: knd   !< Number kind.
  character(*), optional, intent(in)  :: pref  !< Prefixing string.
  integer(I4P), optional, intent(out) :: error !< Error trapping flag: 0 no errors, >0 error occurs.
  real(R4P)                           :: n     !< Number returned.
  integer(I4P)                        :: err   !< Error trapping flag: 0 no errors, >0 error occurs.
  character(len=:), allocatable       :: prefd !< Prefixing string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  read(str, *, iostat=err) n ! Casting of str to n.
  if (err/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    write(stderr, '(A,I1,A)') prefd//' Error: conversion of string "'//str//'" to real failed! real(', kind(knd), ')'
  endif
  if (present(error)) error = err
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction ctor_R4P
Call graph
cton calls ctor_r4p
get_cla_list_varying_r16p calls cton
get_cla_list_varying_i8p calls cton
test_all calls cton
get_cla_from_buffer calls cton
get_cla_list_varying_r4p calls cton
usage calls cton
check_choices calls cton
get_cla_list_varying_i2p calls cton
signature calls cton
get_cla_list_varying_i1p calls cton
get_cla_list_varying_r8p calls cton
get_cla_list_from_buffer calls cton
parse calls cton
get_cla_list_varying_i4p calls cton