errored – FOODIE
errored Subroutine
Source File
private subroutine errored(self, error, pref, switch, val_str, log_value)
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(inout) :: self
CLA data.
integer(kind=I4P), intent(in) :: error
Error occurred.
character(len=*), intent(in), optional :: pref
Prefixing string.
character(len=*), intent(in), optional :: switch
CLA switch name.
character(len=*), intent(in), optional :: val_str
Value string.
character(len=*), intent(in), optional :: log_value
Logical value to be casted.
Description
Trig error occurence and print meaningful message.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: prefd
Prefixing string.
Source Code
  subroutine errored(self, error, pref, switch, val_str, log_value)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Trig error occurence and print meaningful message.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(command_line_argument), intent(inout) :: self      !< CLA data.
  integer(I4P),                 intent(in)    :: error     !< Error occurred.
  character(*), optional,       intent(in)    :: pref      !< Prefixing string.
  character(*), optional,       intent(in)    :: switch    !< CLA switch name.
  character(*), optional,       intent(in)    :: val_str   !< Value string.
  character(*), optional,       intent(in)    :: log_value !< Logical value to be casted.
  character(len=:), allocatable               :: prefd     !< Prefixing string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  self%error = error
  if (self%error/=0) then
    prefd = '' ; if (present(pref)) prefd = pref
    select case(self%error)
    case(ERROR_OPTIONAL_NO_DEF)
      if (self%is_positional) then
        self%error_message = prefd//self%progname//': error: "'//trim(str(n=self%position))//&
                           '-th" positional option has not a default value!'
      else
        self%error_message = prefd//self%progname//': error: named option "'//self%switch//'" has not a default value!'
      endif
    case(ERROR_REQUIRED_M_EXCLUDE)
      self%error_message = prefd//self%progname//': error: named option "'//self%switch//'" cannot exclude others'//&
        ', it being requiredi, only optional ones can!'
    case(ERROR_POSITIONAL_M_EXCLUDE)
      self%error_message = prefd//self%progname//': error: "'//trim(str(n=self%position))//&
        '-th" positional option cannot exclude others, only optional named options can!'
    case(ERROR_NAMED_NO_NAME)
      self%error_message = prefd//self%progname//': error: a non positional optiona must have a switch name!'
    case(ERROR_POSITIONAL_NO_POSITION)
      self%error_message = prefd//self%progname//': error: a positional option must have a position number different from 0!'
    case(ERROR_POSITIONAL_NO_STORE)
      self%error_message = prefd//self%progname//': error: a positional option must have action set to "'//action_store//'"!'
    case(ERROR_M_EXCLUDE)
      self%error_message = prefd//self%progname//': error: the options "'//self%switch//'" and "'//self%m_exclude//&
        '" are mutually exclusive, but both have been passed!'
    case(ERROR_NOT_IN_CHOICES)
      if (self%is_positional) then
        self%error_message = prefd//self%progname//': error: value of "'//trim(str(n=self%position))//&
          '-th" positional option must be chosen in:'
      else
        self%error_message = prefd//self%progname//': error: value of named option "'//self%switch//'" must be chosen in: '
      endif
      self%error_message = self%error_message//'('//self%choices//')'
      self%error_message = self%error_message//' but "'//trim(val_str)//'" has been passed!'
    case(ERROR_MISSING_REQUIRED)
      if (.not.self%is_positional) then
        self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//'" is required!'
      else
        self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//&
          '-th" positional option is required!'
      endif
    case(ERROR_CASTING_LOGICAL)
      self%error_message = prefd//self%progname//': error: cannot convert "'//log_value//'" of option "'//self%switch//&
        '" to logical type!'
    case(ERROR_CHOICES_LOGICAL)
      self%error_message = prefd//self%progname//': error: cannot use "choices" value check for option "'//self%switch//&
        '" it being of logical type! The choices is, by definition of logical, limited to ".true." or ".false."'
    case(ERROR_NO_LIST)
      if (.not.self%is_positional) then
        self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
          '" has not "nargs" value but an array has been passed to "get" method!'
      else
        self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//'-th" positional option '//&
          'has not "nargs" value but an array has been passed to "get" method!'
      endif
    case(ERROR_NARGS_INSUFFICIENT)
      if (.not.self%is_positional) then
        if (self%nargs=='+') then
          self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
            '" requires at least 1 argument but no one remains!'
        else
          self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//'" requires '//&
            trim(adjustl(self%nargs))//' arguments but no enough ones remain!'
        endif
      else
        if (self%nargs=='+') then
          self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//&
            '-th" positional option requires at least 1 argument but no one remains'
        else
          self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//&
            '-th" positional option requires '//&
            trim(adjustl(self%nargs))//' arguments but no enough ones remain!'
        endif
      endif
    case(ERROR_VALUE_MISSING)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" needs a value that is not passed!'
    case(ERROR_UNKNOWN)
      self%error_message = prefd//self%progname//': error: switch "'//trim(adjustl(switch))//'" is unknown!'
    case(ERROR_ENVVAR_POSITIONAL)
      self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//'-th" positional option '//&
        'has "envvar" value that is not allowed for positional option!'
    case(ERROR_ENVVAR_NOT_STORE)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" is an envvar with action different from "'//action_store//'" that is not allowed!'
    case(ERROR_ENVVAR_NARGS)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" is an envvar that is not allowed for list valued option!'
    case(ERROR_STORE_STAR_POSITIONAL)
      self%error_message = prefd//self%progname//': error: "'//trim(str(self%position, .true.))//'-th" positional option '//&
        'has "'//action_store_star//'" action that is not allowed for positional option!'
    case(ERROR_STORE_STAR_NARGS)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" has "'//action_store_star//'" action that is not allowed for list valued option!'
    case(ERROR_STORE_STAR_ENVVAR)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" has "'//action_store_star//'" action that is not allowed for environment variable option!'
    case(ERROR_ACTION_UNKNOWN)
      self%error_message = prefd//self%progname//': error: named option "'//trim(adjustl(self%switch))//&
        '" has unknown "'//self%act//'" action!'
    endselect
    call self%print_error_message
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine errored
Call graph
errored calls str
str calls strf_r4p, str_i2p, str_i4p, strf_i2p, strf_i8p, str_a_r4p, str_r8p, strf_i4p, str_a_i4p, str_r4p, str_bol, str_a_i1p, str_i1p, str_i8p, strf_r8p, str_a_i8p, str_a_i2p, strf_i1p, str_a_r8p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_a_i1p calls str_i1p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p
str_a_r8p calls str_r8p