init – FOODIE
init Subroutine
Source File
private subroutine init(self)
Arguments
Type Intent Optional Attributes Name
class(oscillation_test), intent(inout) :: self
Test.
Description
Initialize test: set Command Line Interface, parse it and check its validity.
Calls
Functions
function is_solver_valid()
Arguments
None
Return Value logical
Return true is the selected solver is available.
Description
Verify if the selected solver is valid.
function is_dt_valid()
Arguments
None
Return Value logical
Return true is the selected time step Dt is valid.
Description
Verify if the selected time step Dt is valid.
function list_solvers() result(list)
Arguments
None
Return Value character(len=:), allocatable
Pretty printed list of available solvers.
Description
List available solvers.
Subroutines
subroutine set_cli()
Arguments
None
Description
Set Command Line Interface.
subroutine parse_cli()
Arguments
None
Description
Parse Command Line Interface and check its validity.
Source Code
  subroutine init(self)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Initialize test: set Command Line Interface, parse it and check its validity.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(oscillation_test), intent(inout) :: self !< Test.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  call set_cli
  call parse_cli
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  contains
    subroutine set_cli()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Set Command Line Interface.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    associate(cli => self%cli)
      call cli%init(progname    = 'oscillation',                                              &
                    authors     = 'Fortran-FOSS-Programmers',                                 &
                    license     = 'GNU GPLv3',                                                &
                    description = 'Test FOODIE library on Oscillation equations integration', &
                    examples    = ["oscillation --solver euler --results  ",                  &
                                   "oscillation --solver ls-runge-kutta -r",                  &
                                   "oscillation --solver adams-bashforth  ",                  &
                                   "oscillation --solver all --plots -r   "])
      call cli%add(switch='--solver', switch_ab='-s', help='ODE solver used', required=.false., def='all', act='store')
      call cli%add(switch='--iterations', help='Number of iterations for implicit solvers', required=.false., act='store', def='5')
      call cli%add(switch='--frequency', switch_ab='-f', help='Oscillation frequency', required=.false., def='1e-4', act='store')
      call cli%add(switch='--ss', nargs='+', help='Stages/steps used', required=.false., def='-1', act='store')
      call cli%add(switch='--time_step', switch_ab='-Dt', nargs='+', help='Time step', required=.false., def='100.d0', act='store')
      call cli%add(switch='--tolerance', switch_ab='-tol', nargs='+', help='Error Tolerance', required=.false., def='0.001d0', &
                   act='store')
      call cli%add(switch='--t_final', switch_ab='-tf', help='Final integration time', required=.false., def='1e6', act='store')
      call cli%add(switch='--results', switch_ab='-r', help='Save results', required=.false., act='store_true', def='.false.')
      call cli%add(switch='--plots', switch_ab='-p', help='Save plots', required=.false., act='store_true', def='.false.')
      call cli%add(switch='--output', help='Output files basename', required=.false., act='store', def='unset')
      call cli%add(switch='--errors_analysis', help='Peform errors analysis', required=.false., act='store_true', def='.false.')
    endassociate
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine set_cli
    subroutine parse_cli()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Parse Command Line Interface and check its validity.
    !-------------------------------------------------------------------------------------------------------------------------------
    character(len=:), allocatable :: valid_solvers_list !< Pretty printed list of available solvers.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    call self%cli%parse(error=self%error)
    call self%cli%get(switch='-s', val=self%solver, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='--iterations', val=self%implicit_iterations, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='-f', val=self%frequency, error=self%error) ; if (self%error/=0) stop
    call self%cli%get_varying(switch='--ss', val=self%stages_steps, error=self%error) ; if (self%error/=0) stop
    call self%cli%get_varying(switch='-Dt', val=self%Dt, error=self%error) ; if (self%error/=0) stop
    call self%cli%get_varying(switch='-tol', val=self%tolerance, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='-tf', val=self%final_time, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='-r', val=self%results, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='-p', val=self%plots, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='--output', val=self%output_cli, error=self%error) ; if (self%error/=0) stop
    call self%cli%get(switch='--errors_analysis', val=self%errors_analysis, error=self%error) ; if (self%error/=0) stop
    if (.not.is_solver_valid()) then
      print "(A)", 'Error: the solver "'//trim(adjustl(self%solver))//'" is unknown!'
      valid_solvers_list = list_solvers()
      print "(A)", valid_solvers_list
      stop
    endif
    if (.not.is_dt_valid()) then
      print "(A)", 'Error: the final integration time must be an exact multiple of the time step used!'
      print "(A)", 'Final integration time: '//str(self%final_time, .true.)
      print "(A)", 'Time step: '//str(self%Dt, .true.)
      stop
    endif
    if (size(self%stages_steps)==2) then
      if (.not.(self%stages_steps(2)>self%stages_steps(1).and.self%stages_steps(1)>=0)) then
        print "(A)", 'Error: when passing a range of stages/steps the valid format must be lower-upper (both positive)!'
        print "(A)", 'Range passed: '//trim(str(self%stages_steps(1), .true.))//'-'//trim(str(self%stages_steps(2), .true.))
        stop
      endif
    endif
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine parse_cli
    function is_solver_valid()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Verify if the selected solver is valid.
    !-------------------------------------------------------------------------------------------------------------------------------
    logical      :: is_solver_valid !< Return true is the selected solver is available.
    integer(I_P) :: s               !< Counter.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    is_solver_valid = .false.
    do s=1, ubound(solvers, dim=1)
      is_solver_valid = (trim(adjustl(self%solver))==trim(adjustl(solvers(s))))
      if (is_solver_valid) exit
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endfunction is_solver_valid
    function is_dt_valid()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Verify if the selected time step Dt is valid.
    !-------------------------------------------------------------------------------------------------------------------------------
    logical      :: is_dt_valid !< Return true is the selected time step Dt is valid.
    integer(I_P) :: t           !< Counter.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    is_dt_valid = .true.
    do t=1, size(self%Dt)
      is_dt_valid = ((self%final_time - int(self%final_time/self%Dt(t), I_P)*self%Dt(t))==0)
      if (.not.is_dt_valid) exit
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endfunction is_dt_valid
    function list_solvers() result(list)
    !-------------------------------------------------------------------------------------------------------------------------------
    !< List available solvers.
    !-------------------------------------------------------------------------------------------------------------------------------
    character(len=:), allocatable :: list !< Pretty printed list of available solvers.
    integer(I_P)                  :: s    !< Solvers counter.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    list = 'Valid solver names are:' // new_line('a')
    do s=1, ubound(solvers, dim=1)
      list = list // '  + ' // trim(adjustl(solvers(s))) // new_line('a')
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endfunction list_solvers
  endsubroutine init
Call graph
init calls parse_cli, set_cli
str calls str_a_i4p, str_a_r4p, str_i4p, str_r8p, strf_i1p, strf_i8p, strf_r4p, str_bol, strf_i4p, str_a_i1p, strf_i2p, str_i8p, str_i1p, strf_r8p, str_a_r8p, str_r4p, str_a_i8p, str_a_i2p, str_i2p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p