init – FOODIE
init Subroutine
Source File
Source Code
init
All Procedures
a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie set_ghost_cells sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
subroutine init(output, solution)
Arguments
Type Intent Optional Attributes Name
character(len=:), intent(out), allocatable :: output
Output files basename.
real(kind=R_P), intent(out), allocatable :: solution(:,:)
Solution at each time step.
Description
Initialize solver local variable from global variables.
Calls
Called By
Source Code
  subroutine init(output, solution)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Initialize solver local variable from global variables.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(len=:), allocatable, intent(OUT) :: output        !< Output files basename.
  real(R_P),        allocatable, intent(OUT) :: solution(:,:) !< Solution at each time step.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (mod(t_final, Dt)/=0) then
    print "(A)", 'Error: the final integration time must be an exact multiple of the time step used!'
    print "(A)", 'Final integration time: '//str(.true.,t_final)
    print "(A)", 'Time step: '//str(.true.,Dt)
    stop
  endif
  if (trim(adjustl(output_cli))/='unset') then
    if (trim(adjustl(solver))/='emd-runge-kutta') then
      output = trim(adjustl(output_cli))//'-'//trim(strz(10,int(t_final/Dt)))//'-time_steps-'//trim(adjustl(solver))
    else
      output = trim(adjustl(output_cli))//'-'//trim(str(.true.,n=tolerance))//'-tolerance-'//trim(adjustl(solver))
    endif
  else
    if (trim(adjustl(solver))/='emd-runge-kutta') then
      output = 'oscillation_integration-'//trim(strz(10,int(t_final/Dt)))//'-time_steps-'//trim(adjustl(solver))
    else
      output = 'oscillation_integration-'//trim(str(.true.,n=tolerance))//'-tolerance-'//trim(adjustl(solver))
    endif
  endif
  if (allocated(solution)) deallocate(solution) ; allocate(solution(0:space_dimension, 0:int(t_final/Dt)))
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine init
Call graph
init calls str, strz
test_emd_rk calls init
test_am calls init
perform_errors_analysis calls init
test_leapfrog calls init
test_ls_rk calls init
test_ab calls init
test_euler calls init
test_tvd_rk calls init
test_abm calls init
integrate_oscillation calls test_emd_rk, test_am, perform_errors_analysis, test_leapfrog, test_ls_rk, test_ab, test_euler, test_tvd_rk, test_abm