interpolate – FOODIE
interpolate Subroutine
Source File
private pure subroutine interpolate(self, S, stencil, location, interpolation)
Arguments
Type Intent Optional Attributes Name
class(weno_interpolator_upwind), intent(in) :: self
WENO interpolator.
integer, intent(in) :: S
Number of stencils actually used.
real(kind=R_P), intent(in) :: stencil(1:,1-S:)
Stencil used for the interpolation, [1:2, 1-S:-1+S].
character(len=*), intent(in) :: location
Location of interpolated value(s): left, right, both.
real(kind=R_P), intent(out) :: interpolation(1:)
Result of the interpolation, [1:2].
Description
Interpolate the stecil input values computing the actual interpolation.
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=R_P), public :: polynomials(1:2,0:S-1)
Polynomial reconstructions.
real(kind=R_P), public :: weights(1:2,0:S-1)
Weights of the stencils.
Subroutines
pure subroutine compute_polynomials(f1, f2, ff, polynomials)
Arguments
Type Intent Optional Attributes Name
integer(kind=I_P), intent(in) :: f1
integer(kind=I_P), intent(in) :: f2
integer(kind=I_P), intent(in) :: ff
Faces to be computed.
real(kind=R_P), intent(out) :: polynomials(1:,0:)
Polynomial reconstructions.
Description
Compute the polynomials reconstructions.
pure subroutine compute_weights(f1, f2, ff, weights)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: f1
integer, intent(in) :: f2
integer, intent(in) :: ff
Faces to be computed.
real(kind=R_P), intent(out) :: weights(1:,0:)
Weights of the stencils, [1:2, 0:S - 1 ].
Description
Compute the stencils weights.
pure subroutine compute_convolution(f1, f2, ff, interpolation)
Arguments
Type Intent Optional Attributes Name
integer(kind=I_P), intent(in) :: f1
integer(kind=I_P), intent(in) :: f2
integer(kind=I_P), intent(in) :: ff
Faces to be computed.
real(kind=R_P), intent(out) :: interpolation(1:)
Left and right (1,2) interface value of reconstructed.
Description
Compute the polynomials convolution.
Source Code
  pure subroutine interpolate(self, S, stencil, location, interpolation)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Interpolate the stecil input values computing the actual interpolation.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(weno_interpolator_upwind), intent(IN)  :: self                      !< WENO interpolator.
  integer,                         intent(IN)  :: S                         !< Number of stencils actually used.
  real(R_P),                       intent(IN)  :: stencil(1:, 1 - S:)       !< Stencil used for the interpolation, [1:2, 1-S:-1+S].
  character(*),                    intent(IN)  :: location                  !< Location of interpolated value(s): left, right, both.
  real(R_P),                       intent(OUT) :: interpolation(1:)         !< Result of the interpolation, [1:2].
  real(R_P)                                    :: polynomials(1:2, 0:S - 1) !< Polynomial reconstructions.
  real(R_P)                                    :: weights(1:2, 0:S - 1)     !< Weights of the stencils.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select case(location)
  case('both', 'b')
    call compute_polynomials(f1=1_I_P, f2=2_I_P, ff=0_I_P, polynomials=polynomials)
    call compute_weights(f1=1_I_P, f2=2_I_P, ff=0_I_P, weights=weights)
    call compute_convolution(f1=1_I_P, f2=2_I_P, ff=0_I_P, interpolation=interpolation)
  case('left', 'l')
    call compute_polynomials(f1=1_I_P, f2=1_I_P, ff=0_I_P, polynomials=polynomials)
    call compute_weights(f1=1_I_P, f2=1_I_P, ff=0_I_P, weights=weights)
    call compute_convolution(f1=1_I_P, f2=1_I_P, ff=0_I_P, interpolation=interpolation)
  case('right', 'r')
    call compute_polynomials(f1=2_I_P, f2=2_I_P, ff=-1_I_P, polynomials=polynomials)
    call compute_weights(f1=2_I_P, f2=2_I_P, ff=-1_I_P, weights=weights)
    call compute_convolution(f1=2_I_P, f2=2_I_P, ff=-1_I_P, interpolation=interpolation)
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  contains
    pure subroutine compute_polynomials(f1, f2, ff, polynomials)
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Compute the polynomials reconstructions.
    !-------------------------------------------------------------------------------------------------------------------------------
    integer(I_P), intent(IN)  :: f1, f2, ff          !< Faces to be computed.
    real(R_P),    intent(OUT) :: polynomials(1:, 0:) !< Polynomial reconstructions.
    integer(I_P)              :: s1, s2, f           !< Counters.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    polynomials = 0.
    do s1 = 0, S - 1 ! stencils loop
      do s2 = 0, S - 1 ! values loop
        do f = f1, f2 ! 1 => left interface (i-1/2), 2 => right interface (i+1/2)
          polynomials(f, s1) = polynomials(f, s1) + self%poly_coef(f, s2, s1) * stencil(f + ff, -s2 + s1)
        enddo
      enddo
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine compute_polynomials
    pure subroutine compute_weights(f1, f2, ff, weights)
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Compute the stencils weights.
    !-------------------------------------------------------------------------------------------------------------------------------
    integer,   intent(IN)  :: f1, f2, ff       !< Faces to be computed.
    real(R_P), intent(OUT) :: weights(1:, 0:)  !< Weights of the stencils, [1:2, 0:S - 1 ].
    real(R_P)              :: IS(1:2, 0:S - 1) !< Smoothness indicators of the stencils.
    real(R_P)              :: a(1:2, 0:S - 1)  !< Alpha coefficients for the weights.
    real(R_P)              :: a_tot(1:2)       !< Sum of the alpha coefficients.
    integer(I_P)           :: s1, s2, s3, f    !< Counters.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    ! computing smoothness indicators
    do s1 = 0, S - 1 ! stencils loop
      do f = f1, f2 ! 1 => left interface (i-1/2), 2 => right interface (i+1/2)
        IS(f, s1) = 0.
        do s2 = 0, S - 1
          do s3 = 0, S - 1
            IS(f, s1) = IS(f, s1) + self%smooth_coef(s3, s2, s1) * stencil(f + ff, s1 - s3) * stencil(f + ff, s1 - s2)
          enddo
        enddo
      enddo
    enddo
    ! computing alfa coefficients
    a_tot = 0.
    do s1 = 0, S - 1 ! stencil loops
      do f = f1, f2 ! 1 => left interface (i-1/2), 2 => right interface (i+1/2)
        a(f, s1) = self%weights_opt(f, s1) * (1./(self%eps + IS(f, s1))**S) ; a_tot(f) = a_tot(f) + a(f, s1)
      enddo
    enddo
    ! computing the weights
    do s1 = 0, S - 1 ! stencils loop
      do f = f1, f2 ! 1 => left interface (i-1/2), 2 => right interface (i+1/2)
        weights(f, s1) = a(f, s1) / a_tot(f)
      enddo
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine compute_weights
    pure subroutine compute_convolution(f1, f2, ff, interpolation)
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Compute the polynomials convolution.
    !-------------------------------------------------------------------------------------------------------------------------------
    integer(I_P), intent(IN)  :: f1, f2, ff        !< Faces to be computed.
    real(R_P),    intent(OUT) :: interpolation(1:) !< Left and right (1,2) interface value of reconstructed.
    integer(I_P)              :: k, f              !< Counters.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    ! computing the convultion
    interpolation = 0.
    do k = 0, S - 1 ! stencils loop
      do f = f1, f2 ! 1 => left interface (i-1/2), 2 => right interface (i+1/2)
        interpolation(f + ff) = interpolation(f + ff) + weights(f, k) * polynomials(f, k)
      enddo
    enddo
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine compute_convolution
  endsubroutine interpolate
Call graph
interpolate calls compute_convolution, compute_polynomials, compute_weights