perform_errors_analysis – FOODIE
perform_errors_analysis Subroutine
Source File
Variables
NDt time_steps tolerances ab_steps emd_rk_stages tvd_rk_stages ls_rk_stages s d output title solution last_step emd_Dt_mean ab_errors abm_errors am_errors emd_rk_errors lf_errors ls_rk_errors tvd_rk_errors ab_orders abm_orders am_orders emd_rk_orders lf_orders ls_rk_orders tvd_rk_orders
Source Code
perform_errors_analysis
All Procedures
a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
subroutine perform_errors_analysis()
Arguments
None
Description
Peform errors analysis.
The analysis is based on the integration of the Oscillation equations with different, decreasing time steps in the range [5000, 2500, 1250, 625, 320, 100]. The error is estimated by the L2 norm of the difference between the exact (\(U_e\)) and the numerical (\(U_{\Delta t}\)) solutions for each time step:
$$ \varepsilon (\Delta t) = || U_e - U_{\Delta t} ||_2 = \sqrt{ \sum_{s=1}^{N_s} { \left(U_e(t_0 + s * \Delta t) - U_{\Delta t}(t_0 + s * \Delta t) \right)^2 }} $$
Using two pairs of subsequent-decreasing time steps solution is possible to estimate the order of accuracy of the solver employed computing the \emph{observed order} of accuracy:
$$ p = \frac{log10 \left(\frac{\varepsilon (\Delta t_1)}{\varepsilon (\Delta t_2)} \right)} {log10 \left(\frac{\Delta t_1}{\Delta t_2} \right)} $$
where \(\frac{\Delta t_1}{\Delta t_2}>1\).
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I_P), public, parameter :: NDt = 6
Number of time steps exercised.
real(kind=R_P), public, parameter :: time_steps(1:NDt) = [5000._R_P,2500._R_P,1250._R_P,625._R_P,320._R_P,100._R_P]
Time steps exercised.
real(kind=R_P), public, parameter :: tolerances(1:NDt) = [0.001_R_P,0.0001_R_P,0.00001_R_P,0.000001_R_P,0.0000001_R_P,0.00000001_R_P]
Tolerances for embedded RK solvers.
integer, public, parameter :: ab_steps = 4
Adams-Bashforth steps number.
integer, public, parameter :: emd_rk_stages = 17
Embedded Runge-Kutta stages number.
integer, public, parameter :: tvd_rk_stages = 5
TVD/SSP Runge-Kutta stages number.
integer, public, parameter :: ls_rk_stages = 14
Low storage Runge-Kutta stages number.
integer(kind=I_P), public :: s
Steps/stages counter.
integer(kind=I_P), public :: d
Time steps-exercised counter.
character(len=:), public, allocatable :: output
Output files basename.
character(len=:), public, allocatable :: title
Output files title.
real(kind=R_P), public, allocatable :: solution(:,:)
Solution at each time step.
integer(kind=I_P), public :: last_step
Last time step computed.
real(kind=R_P), public :: emd_Dt_mean(1:emd_rk_stages,1:NDt)
Mean time resolution for adaptive step methods.
real(kind=R_P), public :: ab_errors(1:space_dimension,1:ab_steps,1:NDt)
Adams-Bashforth errors.
real(kind=R_P), public :: abm_errors(1:space_dimension,1:ab_steps,1:NDt)
Adams-Bashforth-Moulton errors.
real(kind=R_P), public :: am_errors(1:space_dimension,1:ab_steps,1:NDt)
Adams-Moulton errors.
real(kind=R_P), public :: emd_rk_errors(1:space_dimension,1:emd_rk_stages,1:NDt)
TVD/SSP Runge-Kutta errors.
real(kind=R_P), public :: lf_errors(1:space_dimension,1:2,1:NDt)
Leapfrog errors.
real(kind=R_P), public :: ls_rk_errors(1:space_dimension,1:ls_rk_stages,1:NDt)
Low storage Runge-Kutta errors.
real(kind=R_P), public :: tvd_rk_errors(1:space_dimension,1:tvd_rk_stages,1:NDt)
TVD/SSP Runge-Kutta errors.
real(kind=R_P), public :: ab_orders(1:space_dimension,1:ab_steps,1:NDt-1)
Adams-Bashforth orders.
real(kind=R_P), public :: abm_orders(1:space_dimension,1:ab_steps,1:NDt-1)
Adams-Bashforth-Moulton orders.
real(kind=R_P), public :: am_orders(1:space_dimension,1:ab_steps,1:NDt-1)
Adams-Moulton orders.
real(kind=R_P), public :: emd_rk_orders(1:space_dimension,1:emd_rk_stages,1:NDt-1)
Embedded Runge-Kutta orders.
real(kind=R_P), public :: lf_orders(1:space_dimension,1:2,1:NDt-1)
Leapfrog orders.
real(kind=R_P), public :: ls_rk_orders(1:space_dimension,1:ls_rk_stages,1:NDt-1)
Low storage Runge-Kutta orders.
real(kind=R_P), public :: tvd_rk_orders(1:space_dimension,1:tvd_rk_stages,1:NDt-1)
TVD/SSP Runge-Kutta orders.
Source Code
  subroutine perform_errors_analysis()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Peform errors analysis.
  !<
  !< The analysis is based on the integration of the Oscillation equations with different, decreasing time steps in the range
  !< *[5000, 2500, 1250, 625, 320, 100]*. The error is estimated by the L2 norm of the difference between the exact (\(U_e\)) and
  !< the numerical (\(U_{\Delta t}\)) solutions for each time step:
  !<
  !<$$
  !<\varepsilon (\Delta t) = || U_e - U_{\Delta t} ||_2 = \sqrt{ \sum_{s=1}^{N_s} { \left(U_e(t_0 + s * \Delta t) -
  !<U_{\Delta t}(t_0 + s * \Delta t) \right)^2 }}
  !<$$
  !<
  !< Using two pairs of subsequent-decreasing time steps solution is possible to estimate the order of accuracy of the solver
  !< employed computing the \emph{observed order} of accuracy:
  !<
  !<$$
  !<p = \frac{log10 \left( \frac{\varepsilon (\Delta t_1)}{\varepsilon (\Delta t_2)} \right)}
  !<{log10 \left( \frac{\Delta t_1}{\Delta t_2} \right)}
  !<$$
  !<
  !<where \(\frac{\Delta t_1}{\Delta t_2}>1\).
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I_P), parameter       :: NDt=6                               !< Number of time steps exercised.
  real(R_P),    parameter       :: time_steps(1:NDt)=[5000._R_P, &
                                                      2500._R_P, &
                                                      1250._R_P, &
                                                      625._R_P,  &
                                                      320._R_P,  &
                                                      100._R_P]      !< Time steps exercised.
  real(R_P),    parameter       :: tolerances(1:NDt)=[0.001_R_P,     &
                                                      0.0001_R_P,    &
                                                      0.00001_R_P,   &
                                                      0.000001_R_P,  &
                                                      0.0000001_R_P, &
                                                      0.00000001_R_P]  !< Tolerances for embedded RK solvers.
  integer, parameter            :: ab_steps=4                          !< Adams-Bashforth steps number.
  integer, parameter            :: emd_rk_stages=17                    !< Embedded Runge-Kutta stages number.
  integer, parameter            :: tvd_rk_stages=5                     !< TVD/SSP Runge-Kutta stages number.
  integer, parameter            :: ls_rk_stages=14                     !< Low storage Runge-Kutta stages number.
  integer(I_P)                  :: s                                   !< Steps/stages counter.
  integer(I_P)                  :: d                                   !< Time steps-exercised counter.
  character(len=:), allocatable :: output                              !< Output files basename.
  character(len=:), allocatable :: title                               !< Output files title.
  real(R_P), allocatable        :: solution(:,:)                       !< Solution at each time step.
  integer(I_P)                  :: last_step                           !< Last time step computed.
  real(R_P)                     :: emd_Dt_mean(1:emd_rk_stages, 1:NDt) !< Mean time resolution for adaptive step methods.
  ! errors and orders
  real(R_P) :: ab_errors(1:space_dimension, 1:ab_steps, 1:NDt)            !< Adams-Bashforth errors.
  real(R_P) :: abm_errors(1:space_dimension, 1:ab_steps, 1:NDt)           !< Adams-Bashforth-Moulton errors.
  real(R_P) :: am_errors(1:space_dimension, 1:ab_steps, 1:NDt)            !< Adams-Moulton errors.
  real(R_P) :: emd_rk_errors(1:space_dimension, 1:emd_rk_stages, 1:NDt)   !< TVD/SSP Runge-Kutta errors.
  real(R_P) :: lf_errors(1:space_dimension, 1:2, 1:NDt)                   !< Leapfrog errors.
  real(R_P) :: ls_rk_errors(1:space_dimension, 1:ls_rk_stages, 1:NDt)     !< Low storage Runge-Kutta errors.
  real(R_P) :: tvd_rk_errors(1:space_dimension, 1:tvd_rk_stages, 1:NDt)   !< TVD/SSP Runge-Kutta errors.
  real(R_P) :: ab_orders(1:space_dimension, 1:ab_steps, 1:NDt-1)          !< Adams-Bashforth orders.
  real(R_P) :: abm_orders(1:space_dimension, 1:ab_steps, 1:NDt-1)         !< Adams-Bashforth-Moulton orders.
  real(R_P) :: am_orders(1:space_dimension, 1:ab_steps, 1:NDt-1)          !< Adams-Moulton orders.
  real(R_P) :: emd_rk_orders(1:space_dimension, 1:emd_rk_stages, 1:NDt-1) !< Embedded Runge-Kutta orders.
  real(R_P) :: lf_orders(1:space_dimension, 1:2, 1:NDt-1)                 !< Leapfrog orders.
  real(R_P) :: ls_rk_orders(1:space_dimension, 1:ls_rk_stages, 1:NDt-1)   !< Low storage Runge-Kutta orders.
  real(R_P) :: tvd_rk_orders(1:space_dimension, 1:tvd_rk_stages, 1:NDt-1) !< TVD/SSP Runge-Kutta orders.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  ab_errors = -1._R_P     ; ab_orders = 0._R_P
  abm_errors = -1._R_P    ; abm_orders = 0._R_P
  am_errors = -1._R_P     ; am_orders = 0._R_P
  emd_rk_errors = -1._R_P ; emd_rk_orders = 0._R_P
  lf_errors = -1._R_P     ; lf_orders = 0._R_P
  ls_rk_errors = -1._R_P  ; ls_rk_orders = 0._R_P
  tvd_rk_errors = -1._R_P ; tvd_rk_orders = 0._R_P
  if (allocated(solution)) deallocate(solution) ; allocate(solution(0:space_dimension, 0:int(t_final/Dt)))
  results = .true. ! activate results saving
  ! Analyze errors of Adams-Bashforth solvers
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'adams-bashforth'
    call init(output=output, solution=solution)
    do s=1, ab_steps
      title = 'Oscillation equation integration, explicit Adams-Bashforth, t='//str(n=t_final)//' steps='//trim(str(.true., s))
      call ab_solver(steps=s, solution=solution)
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
      ab_errors(:, s, d) = compute_errors(solution=solution)
    enddo
  enddo
  do s=1, ab_steps
    do d=1, NDt-1
      ab_orders(:, s, d) = estimate_orders(solver_error=ab_errors(:, s, d:d+1), Dt_used=time_steps(d:d+1))
    enddo
  enddo
  ! Analyze errors of Adams-Bashforth-Moulton solvers
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'adams-bashforth-moulton'
    call init(output=output, solution=solution)
    do s=1, ab_steps
      title = 'Oscillation equation integration, predictor-corrector Adams-Bashforth-Moulton, t='//str(n=t_final)//&
              ' steps='//trim(str(.true., s))
      call abm_solver(steps=s, solution=solution)
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
      abm_errors(:, s, d) = compute_errors(solution=solution)
    enddo
  enddo
  do s=1, ab_steps
    do d=1, NDt-1
      abm_orders(:, s, d) = estimate_orders(solver_error=abm_errors(:, s, d:d+1), Dt_used=time_steps(d:d+1))
    enddo
  enddo
  ! Analyze errors of Adams-Moulton solvers
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'adams-moulton'
    call init(output=output, solution=solution)
    do s=0, ab_steps-1
      title = 'Oscillation equation integration, implicit Adams-Moulton, t='//str(n=t_final)//&
              ' steps='//trim(str(.true., s))
      if (implicit_iterations>1) then
        call am_solver(steps=s, solution=solution, iterations=implicit_iterations)
      else
        call am_solver(steps=s, solution=solution)
      endif
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
      am_errors(:, s+1, d) = compute_errors(solution=solution)
    enddo
  enddo
  do s=0, ab_steps-1
    do d=1, NDt-1
      am_orders(:, s+1, d) = estimate_orders(solver_error=am_errors(:, s+1, d:d+1), Dt_used=time_steps(d:d+1))
    enddo
  enddo
  ! Analyze errors of embedded Runge-Kutta solvers
  emd_Dt_mean = 0._R_P
  do d=1, NDt ! loop over exercised tolerances
    Dt = time_steps(NDt)
    tolerance = tolerances(d)
    solver = 'emd-runge-kutta'
    call init(output=output, solution=solution)
    do s=1, emd_rk_stages
      if (s==1) cycle ! 1 stages not allowed
      if (s==2) cycle ! 2 stages not suited for test
      if (s==3) cycle ! 3 stages not yet implemented
      if (s==4) cycle ! 4 stages not yet implemented
      if (s==5) cycle ! 5 stages not yet implemented
      if (s==8) cycle ! 8 stages not yet implemented
      if (s==10) cycle ! 10 stages not yet implemented
      if (s==11) cycle ! 11 stages not yet implemented
      if (s==12) cycle ! 12 stages not yet implemented
      if (s==13) cycle ! 13 stages not yet implemented
      if (s==14) cycle ! 14 stages not yet implemented
      if (s==15) cycle ! 15 stages not yet implemented
      if (s==16) cycle ! 16 stages not yet implemented
      title = 'Oscillation equation integration, explicit embedded Runge-Kutta t='//str(n=t_final)//' stages='//trim(str(.true., s))
      if (s==17) then
        call emd_rk_solver(stages=s, tol=tolerances(d)/1000._R_P, solution=solution, last_step=last_step)
      else
        call emd_rk_solver(stages=s, tol=tolerances(d), solution=solution, last_step=last_step)
      endif
      emd_Dt_mean(s, d) = t_final/real(last_step, kind=R_P)
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution(:, 0:last_step))
      emd_rk_errors(:, s, d) = compute_errors(solution=solution(:, 0:last_step))
    enddo
  enddo
  do s=1, emd_rk_stages
    if (s==1) cycle ! 1 stages not allowed
    if (s==2) cycle ! 2 stages not suited for test
    if (s==3) cycle ! 3 stages not yet implemented
    if (s==4) cycle ! 4 stages not yet implemented
    if (s==5) cycle ! 5 stages not yet implemented
    if (s==8) cycle ! 8 stages not yet implemented
    if (s==10) cycle ! 10 stages not yet implemented
    if (s==11) cycle ! 11 stages not yet implemented
    if (s==12) cycle ! 12 stages not yet implemented
    if (s==13) cycle ! 13 stages not yet implemented
    if (s==14) cycle ! 14 stages not yet implemented
    if (s==15) cycle ! 15 stages not yet implemented
    if (s==16) cycle ! 16 stages not yet implemented
    do d=1, NDt-1
      emd_rk_orders(:, s, d) = estimate_orders(solver_error=emd_rk_errors(:, s, d:d+1), Dt_used=emd_Dt_mean(s, d:d+1))
    enddo
  enddo
  ! Analyze errors of leapfrog solver
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'leapfrog'
    call init(output=output, solution=solution)
    title = 'Oscillation equation integration, leapfrog (unfiltered), t='//str(n=t_final)
    call leapfrog_solver(solution=solution)
    call save_results(title=title, basename=output, solution=solution)
    lf_errors(:, 1, d) = compute_errors(solution=solution)
    Dt = time_steps(d)
    solver = 'leapfrog'
    call init(output=output, solution=solution)
    title = 'Oscillation equation integration, leapfrog (RAW filtered), t='//str(n=t_final)
    call leapfrog_solver(solution=solution, raw=.true.)
    call save_results(title=title, basename=output//'-raw', solution=solution)
    lf_errors(:, 2, d) = compute_errors(solution=solution)
  enddo
  do d=1, NDt-1
    lf_orders(:, 1, d) = estimate_orders(solver_error=lf_errors(:, 1, d:d+1), Dt_used=time_steps(d:d+1))
    lf_orders(:, 2, d) = estimate_orders(solver_error=lf_errors(:, 2, d:d+1), Dt_used=time_steps(d:d+1))
  enddo
  ! Analyze errors of low storage Runge-Kutta solvers
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'ls-runge-kutta'
    call init(output=output, solution=solution)
    do s=1, ls_rk_stages
      if (s==2) cycle ! 2 stages not yet implemented
      if (s==3) cycle ! 3 stages not yet implemented
      if (s==4) cycle ! 4 stages not yet implemented
      if (s==8) cycle ! 8 stages not yet implemented
      if (s==9) cycle ! 9 stages not yet implemented
      if (s==10) cycle ! 10 stages not yet implemented
      if (s==11) cycle ! 11 stages not yet implemented
      title = 'Oscillation equation integration, explicit low storage Runge-Kutta, t='//str(n=t_final)//&
        ' steps='//trim(str(.true., s))
      call ls_rk_solver(stages=s, solution=solution)
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
      ls_rk_errors(:, s, d) = compute_errors(solution=solution)
    enddo
  enddo
  do s=1, ls_rk_stages
    if (s==2) cycle ! 2 stages not yet implemented
    if (s==3) cycle ! 3 stages not yet implemented
    if (s==4) cycle ! 4 stages not yet implemented
    if (s==8) cycle ! 8 stages not yet implemented
    if (s==9) cycle ! 9 stages not yet implemented
    if (s==10) cycle ! 10 stages not yet implemented
    if (s==11) cycle ! 11 stages not yet implemented
    do d=1, NDt-1
      ls_rk_orders(:, s, d) = estimate_orders(solver_error=ls_rk_errors(:, s, d:d+1), Dt_used=time_steps(d:d+1))
    enddo
  enddo
  ! Analyze errors of TVD/SSP Runge-Kutta solvers
  do d=1, NDt ! loop over exercised time steps
    Dt = time_steps(d)
    solver = 'tvd-runge-kutta'
    call init(output=output, solution=solution)
    do s=1, tvd_rk_stages
      if (s==4) cycle ! 4 stages not yet implemented
      title = 'Oscillation equation integration, explicit TVD/SSP Runge-Kutta, t='//str(n=t_final)//' steps='//trim(str(.true., s))
      call tvd_rk_solver(stages=s, solution=solution)
      call save_results(title=title, basename=output//'-'//trim(str(.true., s)), solution=solution)
      tvd_rk_errors(:, s, d) = compute_errors(solution=solution)
    enddo
  enddo
  do s=1, tvd_rk_stages
    if (s==4) cycle ! 4 stages not yet implemented
    do d=1, NDt-1
      tvd_rk_orders(:, s, d) = estimate_orders(solver_error=tvd_rk_errors(:, s, d:d+1), Dt_used=time_steps(d:d+1))
    enddo
  enddo
  print "(A)", "Solver & Time Step & f*Dt & Error X & Error Y & Observed Order of Accuracy X & Observed Order of Accuracy Y"
  call print_analysis(solver='adams-bashforth', time_steps=time_steps, errors=ab_errors, orders=ab_orders)
  call print_analysis(solver='adams-bashforth-moulton', time_steps=time_steps, errors=abm_errors, orders=abm_orders)
  call print_analysis(solver='adams-moulton', time_steps=time_steps, errors=am_errors, orders=am_orders)
  call print_analysis(solver='emd-runge-kutta', mean_time_steps=emd_Dt_mean, errors=emd_rk_errors, orders=emd_rk_orders)
  call print_analysis(solver='leapfrog', time_steps=time_steps, errors=lf_errors, orders=lf_orders)
  call print_analysis(solver='ls-runge-kutta', time_steps=time_steps, errors=ls_rk_errors, orders=ls_rk_orders)
  call print_analysis(solver='tvd-runge-kutta', time_steps=time_steps, errors=tvd_rk_errors, orders=tvd_rk_orders)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine perform_errors_analysis
Call graph
perform_errors_analysis calls compute_errors, print_analysis, estimate_orders, init, leapfrog_solver, save_results, ls_rk_solver, str, emd_rk_solver, ab_solver, abm_solver, tvd_rk_solver, am_solver
compute_errors calls exact_solution
print_analysis calls str
init calls str, strz
save_results calls exact_solution
integrate_oscillation calls perform_errors_analysis