save_results – FOODIE
save_results Subroutine
Source File
subroutine save_results(title, basename)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: title
Plot title.
character(len=*), intent(in) :: basename
Output basename.
Description
Save results.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I_P), public :: rawfile
Raw file unit for saving results.
type(pyplot), public :: plt
Plot file handler.
integer(kind=I_P), public :: v
Counter.
Source Code
  subroutine save_results(title, basename)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Save results.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(IN) :: title    !< Plot title.
  character(*), intent(IN) :: basename !< Output basename.
  integer(I_P)             :: rawfile  !< Raw file unit for saving results.
  type(pyplot)             :: plt      !< Plot file handler.
  integer(I_P)             :: v        !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (results.or.plots) final_state = domain%output()
  if (results) then
    open(newunit=rawfile, file=basename//'-'//trim(str(Ni,.true.))//'_cells.dat')
    write(rawfile, '(A)')'TITLE="'//title//'"'
    write(rawfile, '(A)')variables
    write(rawfile, '(A)')'ZONE T="FOODIE: '//trim(str(Ni,.true.))//' cells", I='//trim(str(Ni+1,.true.))//&
                         ', J=1, K=1, DATAPACKING=BLOCK, VARLOCATION=([1]=NODAL,[2-'//trim(str(Np+1,.true.)) //']=CELLCENTERED)'
    write(rawfile, '('//trim(str(Ni+1,.true.))//'('//FR_P//',1X))')xnode
    do v=1, Np
      write(rawfile, '('//trim(str(Ni,.true.))//'('//FR_P//',1X))')final_state(v, :)
    enddo
    if ((av_Ni>0).and.(av_Ni/=Ni)) then
      print "(A)", ' Average solution from Ni: '//trim(str(Ni,.true.))//' to av_Ni: '//trim(str(av_Ni,.true.))
      call average_solution
      write(rawfile, '(A)')'ZONE T="FOODIE: '//trim(str(Ni,.true.))//' cells averaged over '//trim(str(av_Ni,.true.))//&
                           ' cells", I='//trim(str(av_Ni+1,.true.))//&
                           ', J=1, K=1, DATAPACKING=BLOCK, VARLOCATION=([1]=NODAL,[2-'//trim(str(Np+1,.true.)) //']=CELLCENTERED)'
      write(rawfile, '('//trim(str(av_Ni+1,.true.))//'('//FR_P//',1X))')av_xnode
      do v=1, Np
        write(rawfile, '('//trim(str(av_Ni,.true.))//'('//FR_P//',1X))')av_state(v, :)
      enddo
    endif
    close(rawfile)
  endif
  if (plots) then
    call plt%initialize(grid=.true., xlabel='x', title=title)
    do v=1, Ns
      call plt%add_plot(x=xcenter, y=final_state(v, :), label='rho('//trim(str(v,.true.))//')', linestyle='b-', linewidth=1)
    enddo
    call plt%add_plot(x=xcenter, y=final_state(Ns+1, :), label='u', linestyle='r-', linewidth=1)
    call plt%add_plot(x=xcenter, y=final_state(Ns+2, :), label='p', linestyle='g-', linewidth=1)
    call plt%add_plot(x=xcenter, y=final_state(Ns+3, :), label='rho', linestyle='o-', linewidth=1)
    call plt%add_plot(x=xcenter, y=final_state(Ns+4, :), label='gamma', linestyle='c-', linewidth=1)
    call plt%savefig(basename//'-'//trim(str(Ni,.true.))//'_cells.png')
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine save_results
Call graph
save_results calls average_solution, str
str calls str_i2p, strf_i4p, str_i1p, strf_i1p, strf_r4p, strf_i2p, str_a_i4p, str_bol, str_a_r4p, str_a_i2p, str_a_i8p, str_i4p, strf_i8p, str_r4p, str_a_r8p, str_i8p, str_a_i1p, str_r8p, strf_r8p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p
test_leapfrog calls save_results
test_ls_rk calls save_results
test_ab calls save_results
test_tvd_rk calls save_results
test_euler calls save_results
integrate_euler_1d calls test_leapfrog, test_ls_rk, test_ab, test_tvd_rk, test_euler