save_results – FOODIE
save_results Subroutine
Source File
Variables
rawfile ex_sol plt i s
Source Code
save_results
All Procedures
a a a a ab_solver abm_solver add_burgers add_euler add_euler add_euler add_lorenz add_oscillation am_solver average_solution burgers_assign_burgers burgers_assign_real burgers_local_error burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states compute_inter_states compute_inter_states conservative2primitive conservative2primitive conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy destroy_rk dEuler_dt dEuler_dt dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E E E emd_rk_solver estimate_orders euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_assign_real euler_local_error euler_local_error euler_multiply_euler euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_rk H H H H impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init init init init init init init init init init_rk integrate integrate integrate integrate integrate integrate integrate integrate integrate_rk leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_local_error lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver new_Dt oscillation_assign_oscillation oscillation_local_error oscillation_multiply_oscillation oscillation_multiply_real output output output output output output output output p p p p perform_errors_analysis previous_step previous_step previous_step primitive2conservative primitive2conservative primitive2conservative primitive2conservative print_analysis r r r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver riemann_solver riemann_solver save_results save_results save_results save_results save_results save_results save_results save_time_serie save_time_serie save_time_serie save_time_serie set_ghost_cells sub_burgers sub_euler sub_euler sub_euler sub_lorenz sub_oscillation synchronize synchronize test_ab test_ab test_ab test_ab test_abm test_am test_emd_rk test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous update_previous update_previous_steps update_previous_steps update_previous_steps
subroutine save_results(title, basename, solution)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: title
Plot title.
character(len=*), intent(in) :: basename
Output files basename.
real(kind=R_P), intent(in) :: solution(0:,0:)
Solution at each time step.
Description
Save plots of results.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I_P), public :: rawfile
Raw file unit for saving results.
real(kind=R_P), public :: ex_sol(1:space_dimension)
Exact solution.
type(pyplot), public :: plt
Plot file handler.
integer(kind=I_P), public :: i
Counter.
integer(kind=I_P), public :: s
Counter.
Source Code
  subroutine save_results(title, basename, solution)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Save plots of results.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(IN) :: title                     !< Plot title.
  character(*), intent(IN) :: basename                  !< Output files basename.
  real(R_P),    intent(IN) :: solution(0:,0:)           !< Solution at each time step.
  integer(I_P)             :: rawfile                   !< Raw file unit for saving results.
  real(R_P)                :: ex_sol(1:space_dimension) !< Exact solution.
  type(pyplot)             :: plt                       !< Plot file handler.
  integer(I_P)             :: i                         !< Counter.
  integer(I_P)             :: s                         !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (results) then
    open(newunit=rawfile, file=basename//'.dat')
    write(rawfile, '(A)')'TITLE="'//title//'"'
    write(rawfile, '(A)')'VARIABLES="t" "x" "y"'
    write(rawfile, '(A)')'ZONE T="FOODIE time serie"'
    do s=0, ubound(solution, dim=2)
      write(rawfile, '(3('//FR_P//',1X))')(solution(i, s), i=0, space_dimension)
    enddo
    write(rawfile, '(A)')'ZONE T="Exact solution"'
    do s=0, ubound(solution, dim=2)
      ex_sol = exact_solution(t=solution(0, s))
      write(rawfile, '(3('//FR_P//',1X))')solution(0, s), (ex_sol(i), i=1, space_dimension)
    enddo
    close(rawfile)
  endif
  if (plots) then
    call plt%initialize(grid=.true., xlabel='time', title=title, legend=.true.)
    call plt%add_plot(x=solution(0, :), y=solution(1, :), label='u', linestyle='r-', linewidth=1)
    call plt%add_plot(x=solution(0, :), y=solution(2, :), label='v', linestyle='b-', linewidth=1)
    call plt%savefig(basename//'.png')
    call plt%initialize(grid=.true., xlabel='v1', ylabel='v2', title=title//'-path', legend=.true.)
    call plt%add_plot(x=solution(1, :), y=solution(2, :), label='path', linestyle='r-', linewidth=1)
    call plt%savefig('path-'//basename//'.png')
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine save_results
Call graph
save_results calls exact_solution
test_emd_rk calls save_results
test_am calls save_results
perform_errors_analysis calls save_results
test_leapfrog calls save_results
test_ls_rk calls save_results
test_ab calls save_results
test_euler calls save_results
test_tvd_rk calls save_results
test_abm calls save_results
integrate_oscillation calls test_emd_rk, test_am, perform_errors_analysis, test_leapfrog, test_ls_rk, test_ab, test_euler, test_tvd_rk, test_abm