strf_I8P – FOODIE
strf_I8P Function
Source File
private elemental function strf_I8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I8P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI8P)
Returned string containing input number.
Description
Convert integer to string.
Called By
Source Code
  elemental function strf_I8P(fm, n) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in) :: fm  !< Format different from the standard for the kind.
  integer(I8P), intent(in) :: n   !< Integer to be converted.
  character(DI8P)          :: str !< Returned string containing input number.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str, trim(fm)) n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction strf_I8P
Call graph
str calls strf_i8p
solve calls str
test_basic calls str
bctor_r16p calls str
test_choices_logical calls str
bctor_r8p calls str
test_ab calls str, save_results, save_time_serie
bctor_r4p calls str
init calls str, parse_cli
bctoi_i8p calls str
test_all calls str, bcton
bctoi_i4p calls str
bctoi_i1p calls str
save_results calls str
bctoi_i2p calls str
description calls str
test_nested calls str
test_ls_rk calls str, save_results, save_time_serie
sin_reconstruction calls str
test_leapfrog calls str, save_results, save_time_serie
signature calls str
errored calls str
test calls str, solve
usage calls str
save_time_serie calls str
test_hidden calls str
test_tvd_rk calls str, save_results, save_time_serie
test_euler calls str, save_results, save_time_serie
check_choices calls str
test_string calls str
bcton calls bctor_r8p, bctor_r4p, bctoi_i8p, bctoi_i4p, bctoi_i1p, bctoi_i2p
integrate_euler_1d calls test_ab, init, test_ls_rk, test_leapfrog, test_tvd_rk, test_euler