test_ab – FOODIE
test_ab Subroutine
Source File
subroutine test_ab()
Arguments
None
Description
Test explicit Adams-Bashforth class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(tvd_runge_kutta_integrator), public :: rk_integrator
Runge-Kutta integrator.
integer, public, parameter :: rk_stages = 5
Runge-Kutta stages number.
type(euler_1D), public :: rk_stage(1:rk_stages)
Runge-Kutta stages.
type(adams_bashforth_integrator), public :: ab_integrator
Adams-Bashforth integrator.
integer, public, parameter :: ab_steps = 4
Adams-Bashforth steps number.
type(euler_1D), public :: previous(1:ab_steps)
Previous time steps solutions.
integer, public :: step
Time steps counter.
real(kind=R_P), public :: dt
Time step.
real(kind=R_P), public :: t(1:ab_steps)
Times.
integer(kind=I_P), public :: s
AB steps counter.
integer(kind=I_P), public :: ss
AB substeps counter.
integer(kind=I_P), public :: steps_range(1:2)
Steps used.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_ab()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit Adams-Bashforth class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  type(tvd_runge_kutta_integrator) :: rk_integrator         !< Runge-Kutta integrator.
  integer, parameter               :: rk_stages=5           !< Runge-Kutta stages number.
  type(euler_1D)                   :: rk_stage(1:rk_stages) !< Runge-Kutta stages.
  type(adams_bashforth_integrator) :: ab_integrator         !< Adams-Bashforth integrator.
  integer, parameter               :: ab_steps=4            !< Adams-Bashforth steps number.
  type(euler_1D)                   :: previous(1:ab_steps)  !< Previous time steps solutions.
  integer                          :: step                  !< Time steps counter.
  real(R_P)                        :: dt                    !< Time step.
  real(R_P)                        :: t(1:ab_steps)         !< Times.
  integer(I_P)                     :: s                     !< AB steps counter.
  integer(I_P)                     :: ss                    !< AB substeps counter.
  integer(I_P)                     :: steps_range(1:2)      !< Steps used.
  character(len=:), allocatable    :: title                 !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print "(A)", 'Integrating 1D Euler equations by means of Adams-Bashforth class of solvers'
  steps_range = [1, ab_steps] ; if (stages_steps>0) steps_range = [stages_steps, stages_steps]
  do s=steps_range(1), steps_range(2)
    print "(A)", ' AB-'//trim(str(s,.true.))
    title = '1D Euler equations integration, explicit Adams-Bashforth, t='//str(n=t_final)//trim(str( s,.true.))//' steps'
    call ab_integrator%init(steps=s)
    select case(s)
    case(1)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, steps=s, ord=1)
      call rk_integrator%init(stages=s)
    case(2, 3)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, steps=s, ord=3)
      call rk_integrator%init(stages=s)
    case(4, 5)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, steps=s, ord=7)
      call rk_integrator%init(stages=5)
    endselect
    t = 0._R_P
    call save_time_serie(title=title, filename=output//'-'//trim(str( s,.true.))//'-time_serie.dat', t=t(s))
    step = 1
    do while(t(s)<t_final)
      if (verbose) print "(A)", '    Time step: '//str(n=dt)//', Time: '//str(n=t)
      dt = domain%dt(Nmax=0, Tmax=t_final, t=t(s), CFL=0.1_R_P*CFL)
      if (s>=step) then
        ! the time steps from 1 to s - 1 must be computed with other scheme...
        call rk_integrator%integrate(U=domain, stage=rk_stage, dt=dt, t=t(s))
        previous(step) = domain
        if (step>1) then
          t(step) = t(step-1) + dt
        else
          t(step) = dt
        endif
      else
        call ab_integrator%integrate(U=domain, previous=previous(1:s), dt=dt, t=t)
        do ss=1, s-1
          t(ss) = t(ss + 1)
        enddo
        t(s) = t(s) + dt
      endif
      step = step + 1
      call save_time_serie(t=t(s))
    enddo
    call save_time_serie(t=t(s), finish=.true.)
    call save_results(title=title, basename=output//'-'//trim(str( s,.true.)))
  enddo
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_ab
Call graph
test_ab calls save_results, str, save_time_serie
save_results calls str, average_solution
str calls str_i2p, strf_i4p, str_i1p, strf_i1p, strf_r4p, strf_i2p, str_a_i4p, str_bol, str_a_r4p, str_a_i2p, str_a_i8p, str_i4p, strf_i8p, str_r4p, str_a_r8p, str_i8p, str_a_i1p, str_r8p, strf_r8p
save_time_serie calls str
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p
integrate_euler_1d calls test_ab