test_tvd_rk – FOODIE
test_tvd_rk Subroutine
Source File
subroutine test_tvd_rk()
Arguments
None
Description
Test explicit TVD/SSP Runge-Kutta class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(tvd_runge_kutta_integrator), public :: rk_integrator
Runge-Kutta integrator.
integer, public, parameter :: rk_stages = 5
Runge-Kutta stages number.
type(euler_1D), public :: rk_stage(1:rk_stages)
Runge-Kutta stages.
real(kind=R_P), public :: dt
Time step.
real(kind=R_P), public :: t
Time.
integer(kind=I_P), public :: s
RK stages counter.
integer(kind=I_P), public :: stages_range(1:2)
Stages used.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_tvd_rk()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit TVD/SSP Runge-Kutta class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  type(tvd_runge_kutta_integrator) :: rk_integrator         !< Runge-Kutta integrator.
  integer, parameter               :: rk_stages=5           !< Runge-Kutta stages number.
  type(euler_1D)                   :: rk_stage(1:rk_stages) !< Runge-Kutta stages.
  real(R_P)                        :: dt                    !< Time step.
  real(R_P)                        :: t                     !< Time.
  integer(I_P)                     :: s                     !< RK stages counter.
  integer(I_P)                     :: stages_range(1:2)     !< Stages used.
  character(len=:), allocatable    :: title                 !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print "(A)", 'Integrating 1D Euler equations by means of TVD/SSP Runge-Kutta class of solvers'
  stages_range = [1, rk_stages] ; if (stages_steps>0) stages_range = [stages_steps, stages_steps]
  do s=stages_range(1), stages_range(2)
    if (s==4) cycle ! 4 stages not yet implemented
    print "(A)", ' RK-'//trim(str(s,.true.))
    title = '1D Euler equations integration, explicit TVD/SSP Runge-Kutta, t='//str(n=t_final)//trim(str( s,.true.))//' stages'
    call rk_integrator%init(stages=s)
    select case(s)
    case(1)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=1)
    case(2, 3)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=3)
    case(5)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=7)
    endselect
    t = 0._R_P
    call save_time_serie(title=title, filename=output//'-'//trim(str( s,.true.))//'-time_serie.dat', &
                         t=t)
    do while(t<t_final)
      if (verbose) print "(A)", '    Time step: '//str(n=dt)//', Time: '//str(n=t)
      dt = domain%dt(Nmax=0, Tmax=t_final, t=t, CFL=CFL)
      call rk_integrator%integrate(U=domain, stage=rk_stage(1:s), dt=dt, t=t)
      t = t + dt
      call save_time_serie(t=t)
    enddo
    call save_time_serie(t=t, finish=.true.)
    call save_results(title=title, basename=output//'-'//trim(str( s,.true.)))
  enddo
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_tvd_rk
Call graph
test_tvd_rk calls save_results, str, save_time_serie
save_results calls str, average_solution
str calls str_i2p, strf_i4p, str_i1p, strf_i1p, strf_r4p, strf_i2p, str_a_i4p, str_bol, str_a_r4p, str_a_i2p, str_a_i8p, str_i4p, strf_i8p, str_r4p, str_a_r8p, str_i8p, str_a_i1p, str_r8p, strf_r8p
save_time_serie calls str
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p
integrate_euler_1d calls test_tvd_rk