test_ls_rk – FOODiE
test_ls_rk Subroutine
Source File
Variables
rk_integrator rk_stages registers rk_stage dt t s stages_range title
Source Code
test_ls_rk
All Procedures
a a ab_solver add_burgers add_euler add_euler add_lorenz add_oscillation average_solution burgers_assign_burgers burgers_assign_real burgers_multiply_burgers burgers_multiply_real compute_dt compute_dt compute_dt compute_errors compute_inter_states compute_inter_states conservative2primitive conservative2primitive d2Burgers_dx2 dBurgers_dt dBurgers_dx destroy destroy destroy destroy destroy dEuler_dt dEuler_dt dLorenz_dt dOscillation_dt E E estimate_orders euler_assign_euler euler_assign_euler euler_assign_real euler_assign_real euler_multiply_euler euler_multiply_euler euler_multiply_real euler_multiply_real euler_solver exact_solution finalize finalize finalize finalize finalize H H impose_boundary_conditions impose_boundary_conditions init init init init init init init init init init init init init integrate integrate integrate integrate integrate leapfrog_solver lorenz_assign_lorenz lorenz_assign_real lorenz_multiply_lorenz lorenz_multiply_real ls_rk_solver oscillation_assign_oscillation oscillation_multiply_oscillation oscillation_multiply_real output output output output output p p perform_errors_analysis previous_step previous_step previous_step previous_step primitive2conservative primitive2conservative print_analysis r r real_multiply_burgers real_multiply_euler real_multiply_euler real_multiply_lorenz real_multiply_oscillation reconstruct_interfaces_states reconstruct_interfaces_states riemann_solver riemann_solver save_results save_results save_results save_results save_results save_time_serie save_time_serie sub_burgers sub_euler sub_euler sub_lorenz sub_oscillation test_ab test_ab test_ab test_ab test_euler test_euler test_euler test_euler test_leapfrog test_leapfrog test_leapfrog test_leapfrog test_ls_rk test_ls_rk test_ls_rk test_ls_rk test_tvd_rk test_tvd_rk test_tvd_rk test_tvd_rk tvd_rk_solver update_previous_steps update_previous_steps update_previous_steps update_previous_steps
subroutine test_ls_rk()
Arguments
None
Description
Test explicit low storage Runge-Kutta class of ODE solvers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(ls_runge_kutta_integrator), public :: rk_integrator
Runge-Kutta integrator.
integer, public, parameter :: rk_stages = 5
Runge-Kutta stages number.
integer, public, parameter :: registers = 2
Runge-Kutta stages number.
type(euler_1D), public :: rk_stage(1:registers)
Runge-Kutta stages.
real(kind=R_P), public :: dt
Time step.
real(kind=R_P), public :: t
Time.
integer(kind=I_P), public :: s
RK stages counter.
integer(kind=I_P), public :: stages_range(1:2)
Stages used.
character(len=:), public, allocatable :: title
Output files title.
Source Code
  subroutine test_ls_rk()
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Test explicit low storage Runge-Kutta class of ODE solvers.
  !---------------------------------------------------------------------------------------------------------------------------------
  type(ls_runge_kutta_integrator) :: rk_integrator         !< Runge-Kutta integrator.
  integer, parameter              :: rk_stages=5           !< Runge-Kutta stages number.
  integer, parameter              :: registers=2           !< Runge-Kutta stages number.
  type(euler_1D)                  :: rk_stage(1:registers) !< Runge-Kutta stages.
  real(R_P)                       :: dt                    !< Time step.
  real(R_P)                       :: t                     !< Time.
  integer(I_P)                    :: s                     !< RK stages counter.
  integer(I_P)                    :: stages_range(1:2)     !< Stages used.
  character(len=:), allocatable   :: title                 !< Output files title.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  print "(A)", 'Integrating 1D Euler equations by means of low storage (2N) Runge-Kutta class of solvers'
  stages_range = [1, rk_stages] ; if (stages_steps>0) stages_range = [stages_steps, stages_steps]
  do s=stages_range(1), stages_range(2)
    if (s==2) cycle ! 2 stages not yet implemented
    if (s==3) cycle ! 3 stages not yet implemented
    if (s==4) cycle ! 4 stages not yet implemented
    print "(A)", ' RK-'//trim(str(.true.,s))
    title = '1D Euler equations integration, explicit low storage Runge-Kutta, t='//str(n=t_final)//trim(str(.true., s))//' stages'
    call rk_integrator%init(stages=s)
    select case(s)
    case(1)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=1)
    case(2, 3)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=3)
    case(5)
      call domain%init(Ni=Ni, Ns=Ns, Dx=Dx, BC_L=BC_L, BC_R=BC_R, initial_state=initial_state, cp0=cp0, cv0=cv0, ord=7)
    endselect
    t = 0._R_P
    call save_time_serie(title=title, filename=output//'-'//trim(str(.true., s))//'-time_serie.dat', t=t)
    do while(t<t_final)
      if (verbose) print "(A)", '    Time step: '//str(n=dt)//', Time: '//str(n=t)
      dt = domain%dt(Nmax=0, Tmax=t_final, t=t, CFL=CFL)
      call rk_integrator%integrate(U=domain, stage=rk_stage, dt=dt, t=t)
      t = t + dt
      call save_time_serie(t=t)
    enddo
    call save_time_serie(t=t, finish=.true.)
    call save_results(title=title, basename=output//'-'//trim(str(.true., s)))
  enddo
  print "(A)", 'Finish!'
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine test_ls_rk
Call graph
test_ls_rk calls save_results, str, save_time_serie
save_results calls str, average_solution
save_time_serie calls str
integrate_euler_1d calls test_ls_rk