usage – FOODIE
usage Function
Source File
private function usage(self, pref)
Arguments
Type Intent Optional Attributes Name
class(command_line_argument), intent(in) :: self
CLAs group data.
character(len=*), intent(in), optional :: pref
Prefixing string.
Return Value character(len=:), allocatable
Usage string.
Description
Get correct usage.
Calls
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: prefd
Prefixing string.
integer(kind=I4P), public :: a
Counter.
Source Code
  function usage(self, pref)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Get correct usage.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(command_line_argument), intent(in) :: self  !< CLAs group data.
  character(*), optional,       intent(in) :: pref  !< Prefixing string.
  character(len=:), allocatable            :: usage !< Usage string.
  character(len=:), allocatable            :: prefd !< Prefixing string.
  integer(I4P)                             :: a     !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (.not.self%is_hidden) then
    if (self%act==action_store) then
      if (.not.self%is_positional) then
        if (allocated(self%nargs)) then
          usage = ''
          select case(self%nargs)
          case('+')
            usage = usage//' value#1 [value#2...]'
          case('*')
            usage = usage//' [value#1 value#2...]'
          case default
            do a=1, cton(str=trim(adjustl(self%nargs)),knd=1_I4P)
              usage = usage//' value#'//trim(str(a, .true.))
            enddo
          endselect
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            usage = '   '//trim(adjustl(self%switch))//usage//', '//trim(adjustl(self%switch_ab))//usage
          else
            usage = '   '//trim(adjustl(self%switch))//usage
          endif
        else
          if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
            usage = '   '//trim(adjustl(self%switch))//' value, '//trim(adjustl(self%switch_ab))//' value'
          else
            usage = '   '//trim(adjustl(self%switch))//' value'
          endif
        endif
      else
        usage = '  value'
      endif
      if (allocated(self%choices)) then
        usage = usage//', value in: ('//self%choices//')'
      endif
    elseif (self%act==action_store_star) then
      usage = '  [value]'
      if (allocated(self%choices)) then
        usage = usage//', value in: ('//self%choices//')'
      endif
    else
      if (trim(adjustl(self%switch))/=trim(adjustl(self%switch_ab))) then
        usage = '   '//trim(adjustl(self%switch))//', '//trim(adjustl(self%switch_ab))
      else
        usage = '   '//trim(adjustl(self%switch))
      endif
    endif
    prefd = '' ; if (present(pref)) prefd = pref
    usage = prefd//usage
    if (self%is_positional) usage = usage//new_line('a')//prefd//repeat(' ',10)//trim(str(self%position, .true.))//'-th argument'
    if (allocated(self%envvar)) then
      if (self%envvar /= '') then
        usage = usage//new_line('a')//prefd//repeat(' ',10)//'environment variable name "'//trim(adjustl(self%envvar))//'"'
      endif
    endif
    if (.not.self%is_required) then
      if (self%def /= '') then
        usage = usage//new_line('a')//prefd//repeat(' ',10)//'default value '//trim(adjustl(self%def))
      endif
    endif
    if (self%m_exclude/='') usage = usage//new_line('a')//prefd//repeat(' ',10)//'mutually exclude "'//self%m_exclude//'"'
    usage = usage//new_line('a')//prefd//repeat(' ',10)//trim(adjustl(self%help))
  else
    usage = ''
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction usage
Call graph
usage calls cton, str
cton calls ctoi_i1p, ctor_r8p, ctor_r4p, ctoi_i2p, ctoi_i4p, ctoi_i8p
str calls str_a_i4p, str_a_r4p, str_i4p, str_r8p, strf_i1p, strf_i8p, strf_r4p, str_bol, strf_i4p, str_a_i1p, strf_i2p, str_i8p, str_i1p, strf_r8p, str_a_r8p, str_r4p, str_a_i8p, str_a_i2p, str_i2p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p